import { ls } from "@/lib/i18n";

/** Bilingual UI strings for the real-estate storefront kit. */
export const rs = {
  properties: ls("Properties", "پراپرٹیز"),
  featuredProperties: ls("Featured Properties", "نمایاں پراپرٹیز"),
  allListings: ls("All listings", "تمام لسٹنگز"),
  viewAll: ls("View all properties", "تمام پراپرٹیز دیکھیں"),
  buy: ls("Buy", "خریدیں"),
  rent: ls("Rent", "کرایہ"),
  propertyType: ls("Property type", "پراپرٹی کی قسم"),
  anyType: ls("Any type", "کوئی بھی قسم"),
  city: ls("City", "شہر"),
  anyCity: ls("Any city", "کوئی بھی شہر"),
  minPrice: ls("Min price", "کم از کم قیمت"),
  maxPrice: ls("Max price", "زیادہ سے زیادہ قیمت"),
  noMin: ls("No min", "کوئی حد نہیں"),
  noMax: ls("No max", "کوئی حد نہیں"),
  beds: ls("Beds", "بیڈ"),
  anyBeds: ls("Any beds", "کوئی بھی"),
  keyword: ls("Area, society or keyword (e.g. DHA Phase 6)", "علاقہ یا کلیدی لفظ (مثلاً DHA فیز 6)"),
  search: ls("Search", "تلاش کریں"),
  sortBy: ls("Sort by", "ترتیب"),
  newest: ls("Newest first", "تازہ ترین"),
  priceLow: ls("Price: low to high", "قیمت: کم سے زیادہ"),
  priceHigh: ls("Price: high to low", "قیمت: زیادہ سے کم"),
  found: ls("properties found", "پراپرٹیز ملیں"),
  noResults: ls("No properties match your search.", "آپ کی تلاش سے کوئی پراپرٹی نہیں ملی۔"),
  noResultsHint: ls("Try widening the price range or clearing filters.", "قیمت کی حد بڑھائیں یا فلٹرز ہٹائیں۔"),
  clearFilters: ls("Clear filters", "فلٹرز ہٹائیں"),
  perMonth: ls("/month", "/ماہ"),
  bedrooms: ls("Bedrooms", "بیڈ رومز"),
  bathrooms: ls("Bathrooms", "باتھ رومز"),
  area: ls("Area", "رقبہ"),
  purpose: ls("Purpose", "مقصد"),
  type: ls("Type", "قسم"),
  location: ls("Location", "مقام"),
  listed: ls("Listed", "شائع"),
  keyFacts: ls("Key facts", "اہم معلومات"),
  description: ls("Description", "تفصیل"),
  features: ls("Features & amenities", "خصوصیات و سہولیات"),
  map: ls("Location map", "نقشہ"),
  openMap: ls("Open in Google Maps", "گوگل میپس میں کھولیں"),
  video: ls("Video tour", "ویڈیو ٹور"),
  watchVideo: ls("Watch video", "ویڈیو دیکھیں"),
  agent: ls("Listed by", "ایجنٹ"),
  callAgent: ls("Call", "کال کریں"),
  whatsappAgent: ls("WhatsApp", "واٹس ایپ"),
  inquire: ls("Interested? Send an inquiry", "دلچسپی ہے؟ رابطہ کریں"),
  inquiryPlaceholder: ls("I am interested in this property. Please share more details and arrange a visit.", "مجھے اس پراپرٹی میں دلچسپی ہے۔ براہ کرم مزید تفصیلات بتائیں اور وزٹ کا وقت طے کریں۔"),
  sendInquiry: ls("Send Inquiry", "پیغام بھیجیں"),
  backToListings: ls("Back to all properties", "تمام پراپرٹیز پر واپس"),
  share: ls("Share on WhatsApp", "واٹس ایپ پر شیئر کریں"),
  yourName: ls("Full name", "پورا نام"),
  yourPhone: ls("Mobile number", "موبائل نمبر"),
  yourEmail: ls("Email (optional)", "ای میل (اختیاری)"),
  message: ls("Message", "پیغام"),
} as const;
