import { theme, type Blueprint } from "@/templates/catalog/index";

/** 30 ecommerce templates: kitchen 4 · clothing 4 · shoes 4 · gifts 4 · blades 4 · sports 5 · electronics 3 · medical 3 */
export const ecommerceBlueprints: Blueprint[] = [
  /* ───────── KITCHEN (4) ───────── */
  {
    id: "kitchen-01",
    category: "kitchen",
    name: "Copper & Clay",
    tagline: "Warm, editorial kitchenware store",
    description: "A magazine-style store with terracotta accents, big product photography and an ingredient-fresh feel for cookware and crockery brands.",
    style: ["warm", "editorial", "minimal"],
    theme: theme({ primary: "#b45309", primaryFg: "#fff", secondary: "#292524", accent: "#e7c9a9", accentFg: "#292524", bg: "#fffaf5", fg: "#292524", muted: "#f5ebe0", mutedFg: "#78716c", card: "#ffffff", border: "#eaddcf", heading: "Fraunces", body: "Inter", radius: "lg", dark: "#292524" }),
    brief: {
      header: "Centered logo, thin nav below on desktop, cart icon right; top announcement strip in terracotta.",
      hero: "Split hero: oversized serif headline left, tall product image with rounded corners right, small trust badges row.",
      signature: "Collections shown as 3 overlapping polaroid-style cards; featured products in a 4-column grid with soft cream cards.",
      layout: "Generous whitespace, serif headings, cream background, terracotta buttons, footer on dark brown.",
    },
    overrides: { hero: { eyebrow: { en: "Since 2012 · Lahore", ur: "2012 سے · لاہور" } } },
    features: ["Editorial split hero with trust badges", "Overlapping polaroid-style collection cards", "Cream product cards in a 4-column grid"],
    demo: { name: "Copper & Clay Kitchen", city: "Lahore" },
  },
  {
    id: "kitchen-02",
    category: "kitchen",
    name: "ChefLine",
    tagline: "Bold, high-energy appliance store",
    description: "Punchy retail layout with red call-to-actions, deal countdown strip and a dense product grid built for appliances and gadgets.",
    style: ["bold", "retail", "dense"],
    theme: theme({ primary: "#dc2626", primaryFg: "#fff", secondary: "#111827", accent: "#facc15", accentFg: "#111827", bg: "#ffffff", fg: "#111827", muted: "#f3f4f6", mutedFg: "#6b7280", heading: "Poppins", body: "Poppins", radius: "sm", dark: "#111827" }),
    brief: {
      header: "Two-tier header: top bar with phone/WhatsApp, main bar with logo, big search field, cart; category mega-strip below.",
      hero: "Full-width slider with 2 promo slides (uses hero.slides) and side deal tiles.",
      signature: "Yellow 'promo' ribbon with coupon code; product cards with red price tag and 'Add' button visible always.",
      layout: "Compact, retail energy, thick section dividers, dark footer with payment/COD badges.",
    },
    features: ["Retail header with category bar and mobile drawer", "Yellow promo ribbon with coupon code", "Always-visible Add buttons with red price tags"],
    demo: { name: "ChefLine Appliances", city: "Karachi" },
  },
  {
    id: "kitchen-03",
    category: "kitchen",
    name: "Nordic Table",
    tagline: "Scandinavian minimal, airy",
    description: "Ultra-clean layout with sage green accents, thin lines and lots of white space for premium crockery and tableware.",
    style: ["minimal", "premium", "airy"],
    theme: theme({ primary: "#3f6b4f", primaryFg: "#fff", secondary: "#1f2937", accent: "#d9e4dd", accentFg: "#1f2937", bg: "#ffffff", fg: "#1f2937", muted: "#f4f6f4", mutedFg: "#6b7280", border: "#e5e9e6", heading: "DM Sans", body: "DM Sans", radius: "none", dark: "#1f2937" }),
    brief: {
      header: "Sticky transparent header turning white on scroll; left logo, center nav, right icons.",
      hero: "Full-bleed image with a small left-aligned caption card; headline in light weight, one CTA.",
      signature: "Products in a 3-column masonry with hover image swap; collections as text-only list with arrows.",
      layout: "Square corners, hairline borders, sage buttons, lots of breathing room, monochrome footer.",
    },
    features: ["Transparent-to-solid header on scroll", "3-column masonry with hover image swap", "Text-only collections list with arrows"],
    demo: { name: "Nordic Table", city: "Islamabad" },
  },
  {
    id: "kitchen-04",
    category: "kitchen",
    name: "Desi Rasoi",
    tagline: "Playful, colourful, family-friendly",
    description: "Bright teal and mango colours, rounded shapes and friendly copy for everyday kitchen items, tiffins and crockery sets.",
    style: ["playful", "colourful", "friendly"],
    theme: theme({ primary: "#0d9488", primaryFg: "#fff", secondary: "#134e4a", accent: "#fb923c", accentFg: "#1f2937", bg: "#fffdf7", fg: "#1f2937", muted: "#e6f7f5", mutedFg: "#5b6b6a", border: "#d7efeb", heading: "Baloo 2", body: "Nunito", radius: "xl", dark: "#134e4a" }),
    brief: {
      header: "Rounded pill nav, teal background, white logo, orange cart pill with count.",
      hero: "Illustrated-feel hero with big rounded image blob and floating badge chips; bouncy headline font.",
      signature: "Collections as colourful rounded tiles (teal/mango/cream); testimonials as speech bubbles.",
      layout: "Extra-rounded cards, pastel section backgrounds alternating, friendly footer with WhatsApp CTA.",
    },
    features: ["Colourful rounded collection tiles", "Speech-bubble testimonials", "Playful stat cards on a dark band"],
    demo: { name: "Desi Rasoi Store", city: "Faisalabad" },
  },

  /* ───────── CLOTHING (4) ───────── */
  {
    id: "clothing-01",
    category: "clothing",
    name: "Zarnish",
    tagline: "Luxury lawn & pret, editorial fashion",
    description: "High-fashion layout with full-height imagery, serif type and a lookbook grid. Built for lawn, pret and bridal brands.",
    style: ["luxury", "editorial", "fashion"],
    theme: theme({ primary: "#1c1917", primaryFg: "#fff", secondary: "#7c2d12", accent: "#c8a97e", accentFg: "#1c1917", bg: "#ffffff", fg: "#1c1917", muted: "#f7f5f2", mutedFg: "#6b6560", border: "#e8e4df", heading: "Cormorant Garamond", body: "Inter", radius: "none", dark: "#1c1917" }),
    brief: {
      header: "Minimal header: tiny uppercase nav, centered logotype in serif, icons right; hides on scroll down, shows on up.",
      hero: "Full-screen image slider with vertical text 'New Collection', headline bottom-left, thin outline CTA.",
      signature: "Lookbook masonry from gallery; collections as two tall side-by-side panels with hover zoom.",
      layout: "Black/white with gold accent, square corners, uppercase letter-spaced labels, editorial spacing.",
    },
    overrides: { hero: { eyebrow: { en: "Unstitched · Pret · Bridal", ur: "ان اسٹچڈ · پریٹ · برائیڈل" } } },
    features: ["Full-screen scroll-snap hero slider", "Lookbook masonry from the gallery", "Tall side-by-side collection panels with hover zoom"],
    demo: { name: "Zarnish Couture", city: "Lahore" },
  },
  {
    id: "clothing-02",
    category: "clothing",
    name: "StreetForm",
    tagline: "Streetwear for the youth",
    description: "Dark, energetic streetwear store with neon lime accents, marquee text and bold uppercase type for menswear and casual brands.",
    style: ["dark", "streetwear", "bold"],
    theme: theme({ primary: "#c6ff00", primaryFg: "#0a0a0a", secondary: "#ffffff", secondaryFg: "#0a0a0a", accent: "#ff3d81", accentFg: "#fff", bg: "#0a0a0a", fg: "#f5f5f5", muted: "#171717", mutedFg: "#a3a3a3", card: "#141414", border: "#262626", heading: "Bebas Neue", body: "Space Grotesk", radius: "sm", dark: "#000000" }),
    brief: {
      header: "Black sticky header, huge condensed logo, nav in lime on hover, cart count in pink.",
      hero: "Giant headline (Bebas) over a grainy photo, scrolling marquee strip 'FREE DELIVERY ABOVE RS 3000 —'.",
      signature: "Product cards with lime price tags and hover 'QUICK ADD'; promo strip as a diagonal ticker.",
      layout: "Dark mode throughout, hard edges, lime/pink accents, grid lines.",
      motion: "Marquee ticker (.t-marquee), hover scale on cards.",
    },
    features: ["Diagonal promo ticker", "Lime price tags with keyboard-accessible QUICK ADD", "Grid-paper collection cards"],
    demo: { name: "StreetForm", city: "Karachi" },
  },
  {
    id: "clothing-03",
    category: "clothing",
    name: "Gulaab",
    tagline: "Soft, feminine, boutique",
    description: "Blush pinks, rounded cards and script accents for women's boutiques, kurtis and modest fashion.",
    style: ["feminine", "soft", "boutique"],
    theme: theme({ primary: "#be185d", primaryFg: "#fff", secondary: "#4a044e", accent: "#fbcfe8", accentFg: "#4a044e", bg: "#fff8fa", fg: "#3b1f2b", muted: "#fdeef4", mutedFg: "#8a6b78", border: "#f7d6e3", heading: "Playfair Display", body: "Lato", radius: "xl", dark: "#4a044e" }),
    brief: {
      header: "White header with blush border, script-style tagline under logo, pill nav.",
      hero: "Two-column: image collage (3 images with rotations) right, headline + script eyebrow left.",
      signature: "Collections as circular category bubbles; testimonial carousel with big quotation marks.",
      layout: "Rounded-xl cards, soft shadows, pastel section bands, floral divider line.",
    },
    features: ["Circular category bubbles", "Testimonial carousel with big quotation marks", "Soft rounded product cards"],
    demo: { name: "Gulaab Boutique", city: "Multan" },
  },
  {
    id: "clothing-04",
    category: "clothing",
    name: "Khaadi Lane",
    tagline: "Modern heritage, block-print inspired",
    description: "Indigo and mustard palette with pattern accents, grid-based layout that suits unstitched fabric, kurtas and heritage brands.",
    style: ["heritage", "modern", "pattern"],
    theme: theme({ primary: "#1e3a8a", primaryFg: "#fff", secondary: "#0f172a", accent: "#d97706", accentFg: "#fff", bg: "#fbfaf7", fg: "#1f2937", muted: "#f1efe9", mutedFg: "#6b7280", border: "#e5e1d8", heading: "Marcellus", body: "Work Sans", radius: "sm", dark: "#0f172a" }),
    brief: {
      header: "Indigo header band with mustard underline on active nav; logo left, search center.",
      hero: "Asymmetric grid hero: headline card on cream, two stacked product images, a small pattern block.",
      signature: "Section eyebrows sit inside small mustard chips; collections as a 4-tile bento grid.",
      layout: "Bento grids, subtle geometric pattern backgrounds (CSS), indigo footer.",
    },
    features: ["Mustard eyebrow chips (block-print inspired)", "4-tile bento collections grid", "Indigo header with inline search"],
    demo: { name: "Khaadi Lane", city: "Lahore" },
  },

  /* ───────── SHOES (4) ───────── */
  {
    id: "shoes-01",
    category: "shoes",
    name: "Sole Studio",
    tagline: "Sneaker culture, bold and clean",
    description: "Sneaker-store energy: big product silhouettes, size chips, black-and-orange palette and a punchy layout.",
    style: ["bold", "sneaker", "modern"],
    theme: theme({ primary: "#f97316", primaryFg: "#0b0b0b", secondary: "#0b0b0b", accent: "#111827", accentFg: "#fff", bg: "#ffffff", fg: "#0b0b0b", muted: "#f4f4f5", mutedFg: "#71717a", heading: "Oswald", body: "Inter", radius: "md", dark: "#0b0b0b" }),
    brief: {
      header: "White header with thick black bottom border, condensed uppercase nav, orange cart button.",
      hero: "Product-centric hero: huge shoe image floating over an orange circle, headline stacked left.",
      signature: "Size chips shown on product cards on hover; 'New drops' horizontal scroll row.",
      layout: "High contrast, black section headers, orange CTAs, sneaker grid.",
    },
    features: ["Size chips revealed on product cards", "'New drops' horizontal scroll row", "Black-on-white sneaker hero"],
    demo: { name: "Sole Studio", city: "Karachi" },
  },
  {
    id: "shoes-02",
    category: "shoes",
    name: "Kolhapuri Co.",
    tagline: "Handmade leather, artisan warmth",
    description: "Earthy leather tones and craft storytelling for khussa, chappal and handmade leather footwear brands.",
    style: ["artisan", "earthy", "story"],
    theme: theme({ primary: "#7c4a1e", primaryFg: "#fff", secondary: "#3f2a14", accent: "#d4a373", accentFg: "#3f2a14", bg: "#fdf8f1", fg: "#2f2415", muted: "#f3e9dc", mutedFg: "#7a6752", border: "#e8dccb", heading: "Libre Baskerville", body: "Nunito Sans", radius: "md", dark: "#3f2a14" }),
    brief: {
      header: "Cream header, serif logotype, nav with small leather-brown underline.",
      hero: "Image-left, text-right hero with stitched-border card effect (dashed border), craft badges.",
      signature: "'Made by hand' about block with 3 process images; testimonials in leather-brown cards.",
      layout: "Warm paper background, serif headings, stitched dashed dividers.",
    },
    overrides: { hero: { eyebrow: { en: "Handmade in Charsadda & Multan", ur: "چارسدہ اور ملتان میں ہاتھ سے تیار" }, title: { en: "Handmade leather, honest prices", ur: "ہاتھ سے بنا چمڑا، مناسب قیمتیں" } } },
    features: ["'Made by hand' process block with 3 images", "Leather-brown testimonial cards", "Artisan highlights list"],
    demo: { name: "Kolhapuri Co.", city: "Peshawar" },
  },
  {
    id: "shoes-03",
    category: "shoes",
    name: "Stride",
    tagline: "Sporty, fast, performance",
    description: "Electric blue and white, diagonal cuts and motion lines for running, training and school shoes.",
    style: ["sporty", "dynamic", "clean"],
    theme: theme({ primary: "#2563eb", primaryFg: "#fff", secondary: "#0f172a", accent: "#22d3ee", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#eff6ff", mutedFg: "#64748b", heading: "Sora", body: "Sora", radius: "lg", dark: "#0f172a" }),
    brief: {
      header: "Blue gradient header, white nav, glowing cart pill.",
      hero: "Diagonal split (clip-path) hero: blue panel with headline, photo panel right; speed-line decoration.",
      signature: "Feature tiles with big numbers (stats) and gradient borders; product cards with 'Fast delivery' chip.",
      layout: "Angled section edges via clip-path, rounded cards, blue/cyan gradients.",
      motion: "Fade-up on sections, hover lift.",
    },
    features: ["Gradient speed-line hero", "Big-number stat tiles with gradient borders", "'Fast delivery' chips on product cards"],
    demo: { name: "Stride Footwear", city: "Sialkot" },
  },
  {
    id: "shoes-04",
    category: "shoes",
    name: "Maison Heel",
    tagline: "Elegant women's heels and bridal",
    description: "Champagne and black, serif elegance and large detail shots for heels, bridal and formal footwear.",
    style: ["elegant", "luxury", "feminine"],
    theme: theme({ primary: "#111111", primaryFg: "#fff", secondary: "#111111", accent: "#c9a96e", accentFg: "#111111", bg: "#fcfbf9", fg: "#111111", muted: "#f3f0ea", mutedFg: "#6f6a62", border: "#e9e4dc", heading: "Playfair Display", body: "Jost", radius: "none", dark: "#111111" }),
    brief: {
      header: "Centered serif logo, gold hairline under header, uppercase micro-nav.",
      hero: "Three-panel hero (image | text | image) with champagne background; single black CTA.",
      signature: "Collections as gold-framed portraits; lookbook in 2-column oversized grid.",
      layout: "Square corners, gold hairlines, black footer with champagne text.",
    },
    features: ["Gold-framed collection portraits", "Oversized 2-column lookbook", "Serif micro-label typography"],
    demo: { name: "Maison Heel", city: "Lahore" },
  },

  /* ───────── GIFTS (4) ───────── */
  {
    id: "gifts-01",
    category: "gifts",
    name: "Wrapped",
    tagline: "Cheerful gift boxes and flowers",
    description: "Confetti-bright palette, rounded shapes and occasion tiles (Birthday, Eid, Wedding, Anniversary) for gift shops and florists.",
    style: ["cheerful", "colourful", "rounded"],
    theme: theme({ primary: "#e11d48", primaryFg: "#fff", secondary: "#4c0519", accent: "#fde68a", accentFg: "#4c0519", bg: "#fffafb", fg: "#3f1d2b", muted: "#fff1f2", mutedFg: "#8b5a68", border: "#fecdd3", heading: "Quicksand", body: "Nunito", radius: "xl", dark: "#4c0519" }),
    brief: {
      header: "White header, rounded nav pills, red 'Same-day delivery' chip.",
      hero: "Hero with confetti dots background (CSS radial gradients), gift box image right, occasion quick links under headline.",
      signature: "Occasions grid (collections) as pastel tiles with emoji-style icons; 'Add a gift message' callout.",
      layout: "Playful pastels, extra-rounded cards, ribbon-like section dividers.",
    },
    overrides: { collections: { title: { en: "Shop by occasion", ur: "موقع کے مطابق خریداری" }, items: [{ title: { en: "Birthday", ur: "سالگرہ" }, subtitle: { en: "Cakes, balloons, boxes", ur: "کیک، غبارے، گفٹ باکس" }, image: "", href: "/shop?tags=birthday" }, { title: { en: "Eid", ur: "عید" }, subtitle: { en: "Eidi boxes & sweets", ur: "عیدی باکس اور مٹھائیاں" }, image: "", href: "/shop?tags=eid" }, { title: { en: "Wedding", ur: "شادی" }, subtitle: { en: "Nikkah & valima gifts", ur: "نکاح اور ولیمہ کے تحائف" }, image: "", href: "/shop?tags=wedding" }, { title: { en: "Anniversary", ur: "سالگرۂ شادی" }, subtitle: { en: "Flowers & personalised", ur: "پھول اور پرسنلائزڈ تحائف" }, image: "", href: "/shop?tags=anniversary" }] } },
    features: ["Pastel occasions grid with icons", "'Add a gift message' callout", "Cheerful rounded product cards"],
    demo: { name: "Wrapped Gifts", city: "Islamabad" },
  },
  {
    id: "gifts-02",
    category: "gifts",
    name: "Noor Hampers",
    tagline: "Premium hampers, Eid & corporate",
    description: "Deep emerald and gold for luxury hampers, Eid gifting and corporate orders with a bulk-order enquiry emphasis.",
    style: ["luxury", "emerald", "corporate"],
    theme: theme({ primary: "#065f46", primaryFg: "#fff", secondary: "#022c22", accent: "#d4af37", accentFg: "#022c22", bg: "#ffffff", fg: "#062a22", muted: "#eef6f2", mutedFg: "#5f7a70", border: "#d9e8e0", heading: "Cinzel", body: "Lato", radius: "sm", dark: "#022c22" }),
    brief: {
      header: "Emerald header with gold logotype, nav right, 'Corporate orders' outlined button.",
      hero: "Dark emerald hero with gold serif headline, hamper image in gold-bordered frame, trust badges.",
      signature: "Banner section pitched as 'Corporate & bulk gifting' with a lead CTA; gold divider ornaments.",
      layout: "Formal, symmetric, gold hairlines, emerald footer.",
    },
    overrides: { banner: { eyebrow: { en: "Corporate", ur: "کارپوریٹ" }, title: { en: "Bulk & corporate gifting", ur: "بلک اور کارپوریٹ گفٹنگ" }, text: { en: "Branded hampers for clients and teams. Minimum 25 units, custom packaging available.", ur: "کلائنٹس اور ٹیموں کے لیے برانڈڈ ہیمپرز۔ کم از کم 25 یونٹس، کسٹم پیکیجنگ دستیاب۔" }, cta: { label: { en: "Request a quote", ur: "کوٹ حاصل کریں" }, href: "/contact" } } },
    features: ["Corporate & bulk gifting lead banner", "Gold divider ornaments", "Dark header with gold accents"],
    demo: { name: "Noor Hampers", city: "Karachi" },
  },
  {
    id: "gifts-03",
    category: "gifts",
    name: "Little Things",
    tagline: "Minimal, cute stationery & keepsakes",
    description: "Soft lilac, tidy grid and hand-drawn feel for personalised mugs, frames, stationery and small keepsakes.",
    style: ["minimal", "cute", "pastel"],
    theme: theme({ primary: "#7c3aed", primaryFg: "#fff", secondary: "#2e1065", accent: "#fbbf24", accentFg: "#2e1065", bg: "#fdfcff", fg: "#2e1065", muted: "#f3efff", mutedFg: "#7c6f99", border: "#e9e2fb", heading: "Fredoka", body: "Karla", radius: "lg", dark: "#2e1065" }),
    brief: {
      header: "Slim lilac header, rounded logo mark, minimal nav, cart with heart icon.",
      hero: "Centered hero with big rounded headline, product mosaic (6 small images) below.",
      signature: "'Personalise it' step strip; product cards with dashed hover border.",
      layout: "Tidy 4-col grids, pastel lilac bands, hand-drawn underline on headings (CSS).",
    },
    features: ["'Personalise it' step strip", "Dashed hover border on product cards", "Compact occasions icon grid"],
    demo: { name: "Little Things", city: "Rawalpindi" },
  },
  {
    id: "gifts-04",
    category: "gifts",
    name: "Bloom & Box",
    tagline: "Florist-first with dark botanical mood",
    description: "Deep green botanical mood with photography-first sections for florists offering bouquets, gift boxes and same-day delivery.",
    style: ["botanical", "dark", "photographic"],
    theme: theme({ primary: "#e9c46a", primaryFg: "#1b2a24", secondary: "#f1f5f2", secondaryFg: "#1b2a24", accent: "#f4a261", accentFg: "#1b2a24", bg: "#0f1f19", fg: "#f1f5f2", muted: "#16302a", mutedFg: "#a7b8b1", card: "#14291f", border: "#254338", heading: "Cormorant Garamond", body: "Manrope", radius: "md", dark: "#0a1512" }),
    brief: {
      header: "Transparent header over hero, thin gold nav; solid dark on scroll.",
      hero: "Full-bleed floral image with dark gradient, serif headline, gold CTA and 'Order by 4pm for same-day' note.",
      signature: "Featured products as large image-first cards with hover overlay price; promo as gold ribbon.",
      layout: "Dark botanical theme, gold accents, serif headings, generous imagery.",
    },
    features: ["Dark botanical mood with fixed header", "Image-first product cards with reveal price row", "Gold promo ribbon"],
    demo: { name: "Bloom & Box", city: "Lahore" },
  },

  /* ───────── SWORDS & KNIVES (4) ───────── */
  {
    id: "blades-01",
    category: "blades",
    name: "Damascus Forge",
    tagline: "Dark, forge-lit craftsmanship",
    description: "Charcoal and ember palette, steel textures and a craftsmanship story for Damascus knife makers and export sellers.",
    style: ["dark", "craft", "premium"],
    theme: theme({ primary: "#f59e0b", primaryFg: "#1a1a1a", secondary: "#e5e5e5", secondaryFg: "#1a1a1a", accent: "#b91c1c", accentFg: "#fff", bg: "#141414", fg: "#ececec", muted: "#1f1f1f", mutedFg: "#a3a3a3", card: "#1b1b1b", border: "#2e2e2e", heading: "Cinzel", body: "Inter", radius: "sm", dark: "#0a0a0a" }),
    brief: {
      header: "Black header, engraved-style serif logo, amber nav underline, cart.",
      hero: "Hero with dark forge photo, ember glow gradient, headline in Cinzel, 'Worldwide shipping' badge.",
      signature: "Craft section as horizontal timeline with numbered steps; product cards show steel type chip (Damascus / 1095).",
      layout: "Dark, metallic borders, amber accents, specs tables prominent.",
    },
    features: ["Forge-lit dark theme", "Craft timeline with numbered steps", "Steel-type chip on product cards"],
    demo: { name: "Damascus Forge Wazirabad", city: "Wazirabad" },
  },
  {
    id: "blades-02",
    category: "blades",
    name: "Steelcraft Heritage",
    tagline: "Museum-like, light, collectors",
    description: "Light parchment background, serif typography and gallery-style product presentation for swords, collectibles and replicas.",
    style: ["light", "heritage", "gallery"],
    theme: theme({ primary: "#7f1d1d", primaryFg: "#fff", secondary: "#1c1917", accent: "#a16207", accentFg: "#fff", bg: "#faf7f2", fg: "#1c1917", muted: "#f0ebe1", mutedFg: "#6d665b", border: "#e2dacb", heading: "EB Garamond", body: "Source Sans 3", radius: "none", dark: "#1c1917" }),
    brief: {
      header: "Parchment header, centered serif logo with small crest icon, nav below.",
      hero: "Museum plaque style: centered headline, sword image on neutral plinth, two CTAs.",
      signature: "Products presented as 'exhibits' with catalogue numbers; craft section as two-column essay with images.",
      layout: "Square corners, thin rules, catalogue feel, maroon accents.",
    },
    features: ["Centred masthead logo", "Products presented as catalogued exhibits", "Two-column craft essay with images"],
    demo: { name: "Steelcraft Heritage", city: "Wazirabad" },
  },
  {
    id: "blades-03",
    category: "blades",
    name: "Edge Outdoors",
    tagline: "Rugged outdoor & hunting knives",
    description: "Olive and blaze-orange, rugged type and gear-store layout for hunting, camping and tactical knives.",
    style: ["rugged", "outdoor", "bold"],
    theme: theme({ primary: "#ea580c", primaryFg: "#fff", secondary: "#1f2a1c", accent: "#84cc16", accentFg: "#1f2a1c", bg: "#f7f7f2", fg: "#1f2a1c", muted: "#e9ebe2", mutedFg: "#5f6b58", border: "#d9ddd0", heading: "Barlow Condensed", body: "Barlow", radius: "sm", dark: "#1f2a1c" }),
    brief: {
      header: "Olive header, condensed uppercase nav, orange 'Shop' button.",
      hero: "Outdoor photo hero with topographic-line overlay (CSS), headline in condensed caps, spec badges.",
      signature: "Product cards with blade length / steel / weight micro-specs row; features as icon list in olive.",
      layout: "Gear-store grid, sharp corners, orange CTAs, dark olive footer.",
    },
    features: ["Blade length / steel / weight micro-specs on cards", "Olive icon feature list", "Rugged full-bleed hero"],
    demo: { name: "Edge Outdoors", city: "Sialkot" },
  },
  {
    id: "blades-04",
    category: "blades",
    name: "Kitchen Steel",
    tagline: "Chef knives, clean and modern",
    description: "Cool grey and steel blue, minimal product focus for chef knives, cleavers and kitchen cutlery sets.",
    style: ["minimal", "modern", "steel"],
    theme: theme({ primary: "#0f766e", primaryFg: "#fff", secondary: "#0f172a", accent: "#94a3b8", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "Manrope", body: "Manrope", radius: "md", dark: "#0f172a" }),
    brief: {
      header: "White header, thin nav, teal underline, cart right.",
      hero: "Minimal hero: knife on white, headline left, feature chips (Full tang, Hand sharpened).",
      signature: "Comparison-style features grid; craft section shown as 3 vertical cards.",
      layout: "Clean grid, steel-grey accents, teal buttons.",
    },
    features: ["Comparison-style features grid", "3 vertical craft cards", "Clean knife-on-white hero with chips"],
    demo: { name: "Kitchen Steel", city: "Wazirabad" },
  },

  /* ───────── SPORTS (5) ───────── */
  {
    id: "sports-01",
    category: "sports",
    name: "Pitch Pro",
    tagline: "Cricket-first sports store",
    description: "Green-and-white cricket energy, bat-and-ball hero and category tiles for cricket, football and fitness gear.",
    style: ["sporty", "cricket", "bold"],
    theme: theme({ primary: "#15803d", primaryFg: "#fff", secondary: "#052e16", accent: "#facc15", accentFg: "#052e16", bg: "#ffffff", fg: "#052e16", muted: "#f0fdf4", mutedFg: "#4b5f52", heading: "Rubik", body: "Rubik", radius: "md", dark: "#052e16" }),
    brief: {
      header: "Green header, white bold nav, yellow cart.",
      hero: "Big action photo hero with headline in heavy Rubik, category quick-links (Cricket, Football, Fitness).",
      signature: "Brands strip with logos; 'Top picks' horizontal scroller.",
      layout: "Energetic, green bands, yellow CTAs, angled dividers.",
    },
    features: ["Cricket-first hero with category nav", "Brands logo strip", "'Top picks' horizontal scroller"],
    demo: { name: "Pitch Pro Sports", city: "Sialkot" },
  },
  {
    id: "sports-02",
    category: "sports",
    name: "IronWorks",
    tagline: "Fitness equipment, dark & heavy",
    description: "Charcoal and red for gym equipment and fitness stores: dumbbells, racks, supplements.",
    style: ["dark", "fitness", "heavy"],
    theme: theme({ primary: "#ef4444", primaryFg: "#fff", secondary: "#f5f5f5", secondaryFg: "#0a0a0a", accent: "#fbbf24", accentFg: "#0a0a0a", bg: "#0f0f0f", fg: "#f5f5f5", muted: "#1a1a1a", mutedFg: "#a3a3a3", card: "#161616", border: "#2a2a2a", heading: "Anton", body: "Inter", radius: "sm", dark: "#000000" }),
    brief: {
      header: "Black header, Anton logo, red underline nav.",
      hero: "Dark gym photo, red diagonal stripe, huge headline, stats row under hero.",
      signature: "Product cards with weight/size chips; features as red-numbered list.",
      layout: "Dark, aggressive, red accents, big type.",
    },
    features: ["Dark heavy-metal hero", "Weight/size chips on product cards", "Red-numbered features list"],
    demo: { name: "IronWorks Fitness Store", city: "Lahore" },
  },
  {
    id: "sports-03",
    category: "sports",
    name: "Active Kids",
    tagline: "Kids sports & school gear, friendly",
    description: "Bright blue and orange, rounded and friendly for kids' sportswear, school sports kits and academies.",
    style: ["friendly", "bright", "kids"],
    theme: theme({ primary: "#0284c7", primaryFg: "#fff", secondary: "#0c4a6e", accent: "#fb923c", accentFg: "#0c4a6e", bg: "#ffffff", fg: "#0c4a6e", muted: "#f0f9ff", mutedFg: "#5b7a8c", heading: "Baloo 2", body: "Nunito", radius: "xl", dark: "#0c4a6e" }),
    brief: {
      header: "Blue rounded header, playful logo, orange cart pill.",
      hero: "Rounded blob image, bouncy headline, three colourful badges.",
      signature: "Collections as circular icons; testimonials as speech bubbles.",
      layout: "Rounded, bright, alternating pastel bands.",
    },
    features: ["Circular icon collections", "Speech-bubble testimonials", "Bright blob-shaped banner"],
    demo: { name: "Active Kids", city: "Islamabad" },
  },
  {
    id: "sports-04",
    category: "sports",
    name: "Summit Gear",
    tagline: "Outdoor, trekking & camping",
    description: "Forest green and sand for trekking, camping and northern-areas outdoor gear stores.",
    style: ["outdoor", "earthy", "adventure"],
    theme: theme({ primary: "#166534", primaryFg: "#fff", secondary: "#1c1917", accent: "#d97706", accentFg: "#fff", bg: "#fbfaf6", fg: "#1c1917", muted: "#f0eee6", mutedFg: "#6b675e", border: "#e2dfd3", heading: "Bricolage Grotesque", body: "Inter", radius: "md", dark: "#1c1917" }),
    brief: {
      header: "Sand header, green logo, nav with mountain icon accent.",
      hero: "Mountain photo hero with gradient, headline, 'Gear checklist' CTA.",
      signature: "Collections as wide landscape tiles; features with trail icons.",
      layout: "Earthy, wide imagery, green CTAs.",
    },
    features: ["Wide landscape collection tiles", "Trail-icon features", "Outdoor hero with altitude badge"],
    demo: { name: "Summit Gear", city: "Islamabad" },
  },
  {
    id: "sports-05",
    category: "sports",
    name: "Court Club",
    tagline: "Racket sports & team kits, clean",
    description: "Navy and neon yellow, clean grid for badminton, tennis, padel and team-kit customization stores.",
    style: ["clean", "modern", "team"],
    theme: theme({ primary: "#1e3a8a", primaryFg: "#fff", secondary: "#0f172a", accent: "#d9f99d", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "Archivo", body: "Archivo", radius: "lg", dark: "#0f172a" }),
    brief: {
      header: "White header, navy nav, neon 'Team kits' button.",
      hero: "Split hero with neon accent shape behind image; headline + two CTAs.",
      signature: "Banner pitched as 'Custom team kits' with lead CTA; brands strip.",
      layout: "Clean, navy/neon, rounded-lg cards.",
    },
    overrides: { banner: { eyebrow: { en: "Teams & academies", ur: "ٹیمیں اور اکیڈمیاں" }, title: { en: "Custom team kits & printing", ur: "کسٹم ٹیم کٹس اور پرنٹنگ" }, text: { en: "Jerseys, numbers and logos for your club or school team. Bulk discounts from 15 pieces.", ur: "آپ کے کلب یا اسکول ٹیم کے لیے جرسیاں، نمبر اور لوگو۔ 15 پیس سے بلک ڈسکاؤنٹ۔" }, cta: { label: { en: "Request a quote", ur: "کوٹ حاصل کریں" }, href: "/contact" } } },
    features: ["Custom team-kits lead banner", "Brands strip", "Clean court-line grid layout"],
    demo: { name: "Court Club", city: "Karachi" },
  },

  /* ───────── ELECTRONICS (3) ───────── */
  {
    id: "electronics-01",
    category: "electronics",
    name: "Voltify",
    tagline: "Modern tech store, blue & clean",
    description: "Clean tech-retail layout with blue accents, spec highlights and brand strip for mobiles, laptops and accessories.",
    style: ["modern", "tech", "clean"],
    theme: theme({ primary: "#2563eb", primaryFg: "#fff", secondary: "#0f172a", accent: "#f59e0b", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "Plus Jakarta Sans", body: "Inter", radius: "lg", dark: "#0f172a" }),
    brief: {
      header: "Two-tier: top bar with 'Official warranty · COD nationwide', main bar with logo, search, cart; category chips row.",
      hero: "Product slider hero with spec bullets and price-from tag; side tiles for 'Mobiles' and 'Laptops'.",
      signature: "Product cards show 2-3 key specs; brands strip; warranty features block.",
      layout: "Retail grid, blue CTAs, light grey bands.",
    },
    features: ["Key specs on product cards", "Header search bar", "Warranty features block"],
    demo: { name: "Voltify Electronics", city: "Lahore" },
  },
  {
    id: "electronics-02",
    category: "electronics",
    name: "Nightshift",
    tagline: "Gaming & gadgets, dark neon",
    description: "Dark UI with violet/cyan neon glows for gaming PCs, peripherals and gadgets.",
    style: ["dark", "gaming", "neon"],
    theme: theme({ primary: "#8b5cf6", primaryFg: "#fff", secondary: "#e2e8f0", secondaryFg: "#0b0b12", accent: "#22d3ee", accentFg: "#0b0b12", bg: "#0b0b12", fg: "#e2e8f0", muted: "#151527", mutedFg: "#94a3b8", card: "#12122a", border: "#262646", heading: "Orbitron", body: "Inter", radius: "md", dark: "#06060c" }),
    brief: {
      header: "Dark header with neon gradient bottom border, Orbitron logo.",
      hero: "Dark hero with glowing gradient orbs, product image, neon CTA.",
      signature: "Glow-border product cards; specs as monospace chips.",
      layout: "Dark neon, gradient borders, grid.",
      motion: "Subtle glow pulse on CTA.",
    },
    features: ["Neon glow-border product cards", "Monospace spec chips", "Dark gaming palette"],
    demo: { name: "Nightshift Gaming", city: "Karachi" },
  },
  {
    id: "electronics-03",
    category: "electronics",
    name: "HomeVolt",
    tagline: "Home appliances, trustworthy & warm",
    description: "Warm neutral palette and trust-first layout for home appliances, solar and inverters with installation support.",
    style: ["trust", "warm", "appliances"],
    theme: theme({ primary: "#0f766e", primaryFg: "#fff", secondary: "#134e4a", accent: "#f97316", accentFg: "#fff", bg: "#fbfbf9", fg: "#1f2937", muted: "#f0f4f2", mutedFg: "#5f6f6a", heading: "Figtree", body: "Figtree", radius: "lg", dark: "#134e4a" }),
    brief: {
      header: "Cream header, teal logo, phone number prominent, cart.",
      hero: "Split hero with appliance image and 'Installation included' badges; trust row (warranty, COD, service).",
      signature: "Banner as 'Solar & inverter solutions' lead capture; features with service icons.",
      layout: "Warm neutral, teal CTAs, orange highlights.",
    },
    overrides: { banner: { eyebrow: { en: "Solar", ur: "سولر" }, title: { en: "Solar & inverter packages", ur: "سولر اور انورٹر پیکجز" }, text: { en: "Beat load-shedding with net-metering-ready solar systems. Free site survey in city.", ur: "نیٹ میٹرنگ کے لیے تیار سولر سسٹمز کے ساتھ لوڈ شیڈنگ کو شکست دیں۔ شہر میں مفت سائٹ سروے۔" }, cta: { label: { en: "Get a free survey", ur: "مفت سروے حاصل کریں" }, href: "/contact" } } },
    features: ["Solar & inverter lead-capture banner", "Service-icon features", "Click-to-call CTA"],
    demo: { name: "HomeVolt Appliances", city: "Gujranwala" },
  },

  /* ───────── MEDICAL STORES (3) ───────── */
  {
    id: "medical-01",
    category: "medical",
    name: "CarePlus Pharmacy",
    tagline: "Clean clinical blue, trust-first",
    description: "Clinical white-and-blue layout with prescription upload front and centre, category chips and pharmacist trust badges.",
    style: ["clinical", "clean", "trust"],
    theme: theme({ primary: "#0369a1", primaryFg: "#fff", secondary: "#0c4a6e", accent: "#22c55e", accentFg: "#052e16", bg: "#ffffff", fg: "#0f172a", muted: "#f0f9ff", mutedFg: "#5b7a8c", heading: "Inter", body: "Inter", radius: "md", dark: "#0c4a6e" }),
    brief: {
      header: "White header, blue cross logo mark, search bar, 'Upload prescription' green button, cart.",
      hero: "Two CTAs hero (Shop / Upload prescription), pharmacist photo, trust badges (Licensed, Genuine, Delivery).",
      signature: "Prescription CTA block with 3 steps; categories as icon chips (Medicines, Baby care, Vitamins, Devices).",
      layout: "Clean, high legibility, blue/green.",
    },
    features: ["3-step prescription CTA block", "Category icon chips", "Clinical blue trust header"],
    demo: { name: "CarePlus Pharmacy", city: "Lahore" },
  },
  {
    id: "medical-02",
    category: "medical",
    name: "Sehat Store",
    tagline: "Friendly, green wellness",
    description: "Soft green wellness mood with rounded cards, Urdu-friendly type and a family-pharmacy feel.",
    style: ["friendly", "green", "wellness"],
    theme: theme({ primary: "#16a34a", primaryFg: "#fff", secondary: "#14532d", accent: "#fbbf24", accentFg: "#14532d", bg: "#f9fdf9", fg: "#14532d", muted: "#ecfdf5", mutedFg: "#4d7c5e", border: "#d1fae5", heading: "Nunito", body: "Nunito", radius: "xl", dark: "#14532d" }),
    brief: {
      header: "Green rounded header, white logo, WhatsApp order button.",
      hero: "Rounded image, friendly headline, 'Order by WhatsApp' and 'Upload prescription' CTAs.",
      signature: "Wellness categories as pastel rounded tiles; prescription CTA as a card with icon steps.",
      layout: "Rounded, pastel green, warm and accessible.",
    },
    features: ["Pastel wellness category tiles", "Prescription card with icon steps", "Rounded green header pills"],
    demo: { name: "Sehat Medical Store", city: "Rawalpindi" },
  },
  {
    id: "medical-03",
    category: "medical",
    name: "MediDash",
    tagline: "Fast delivery app-style",
    description: "App-like layout with sticky search, quick reorder emphasis, delivery ETA and a bold red-white palette.",
    style: ["app-like", "fast", "bold"],
    theme: theme({ primary: "#dc2626", primaryFg: "#fff", secondary: "#111827", accent: "#0ea5e9", accentFg: "#fff", bg: "#ffffff", fg: "#111827", muted: "#f9fafb", mutedFg: "#6b7280", heading: "Urbanist", body: "Inter", radius: "lg", dark: "#111827" }),
    brief: {
      header: "Compact header with big search input and 'Deliver to: city' chip; cart.",
      hero: "App-style hero: search-first card with 'Search medicines by name or generic', ETA badge '60-min delivery'.",
      signature: "Category chips scroll row; 'Upload prescription' floating card; features as delivery-time steps.",
      layout: "Mobile-first, card-based, red CTAs.",
    },
    features: ["App-style category chip scroll row", "Floating 'Upload prescription' card", "Delivery-time step features"],
    demo: { name: "MediDash", city: "Karachi" },
  },
];
