import { theme, type Blueprint } from "@/templates/catalog/index";

/** 10 recruiting agency templates */
export const recruitingBlueprints: Blueprint[] = [
  {
    id: "recruiting-01",
    category: "recruiting",
    name: "TalentBridge",
    tagline: "Corporate navy, job-search first",
    description: "Trust-first corporate layout with a prominent job search hero, stats and industries grid for licensed overseas employment promoters.",
    style: ["corporate", "trust", "navy"],
    theme: theme({ primary: "#1e40af", primaryFg: "#fff", secondary: "#0f172a", accent: "#f59e0b", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "Plus Jakarta Sans", body: "Inter", radius: "md", dark: "#0f172a" }),
    brief: {
      header: "White header with navy top strip (licence no., phone), logo, nav, 'Submit CV' button.",
      hero: "Navy gradient hero with JobSearchBar card (keyword + location), stats row beneath.",
      signature: "Industries grid with icon tiles; employers CTA as split banner.",
      layout: "Corporate grid, navy/amber, card-based.",
    },
    demo: { name: "TalentBridge Overseas", city: "Lahore" },
  },
  {
    id: "recruiting-02",
    category: "recruiting",
    name: "GulfGate",
    tagline: "Gulf-focused, gold & green",
    description: "Green and gold with Gulf skyline imagery and country tabs for Saudi/UAE/Qatar recruitment agencies.",
    style: ["gulf", "green", "gold"],
    theme: theme({ primary: "#047857", primaryFg: "#fff", secondary: "#064e3b", accent: "#d4af37", accentFg: "#064e3b", bg: "#ffffff", fg: "#052e16", muted: "#ecfdf5", mutedFg: "#4b6b5c", heading: "Cinzel", body: "Lato", radius: "sm", dark: "#064e3b" }),
    brief: {
      header: "Green header, gold logotype, nav, WhatsApp button.",
      hero: "Skyline photo, gold serif headline, country chips (Saudi Arabia, UAE, Qatar, Oman) linking to /jobs?country=.",
      signature: "Featured jobs grouped with country flags/labels; process as gold-numbered steps.",
      layout: "Formal, gold hairlines, green sections.",
    },
    overrides: { hero: { eyebrow: { en: "Saudi · UAE · Qatar · Oman", ur: "سعودیہ · یو اے ای · قطر · عمان" }, title: { en: "Verified Gulf jobs for Pakistani workers", ur: "پاکستانی کارکنوں کے لیے تصدیق شدہ خلیجی نوکریاں" } } },
    demo: { name: "GulfGate Recruitment", city: "Rawalpindi" },
  },
  {
    id: "recruiting-03",
    category: "recruiting",
    name: "HireHub",
    tagline: "Modern startup, violet gradient",
    description: "Startup-style landing with violet gradients, rounded cards and a job-board feel for tech and white-collar recruiting firms.",
    style: ["modern", "startup", "gradient"],
    theme: theme({ primary: "#6d28d9", primaryFg: "#fff", secondary: "#1e1b4b", accent: "#22d3ee", accentFg: "#1e1b4b", bg: "#ffffff", fg: "#1e1b4b", muted: "#f5f3ff", mutedFg: "#6b7280", heading: "Sora", body: "Sora", radius: "xl", dark: "#1e1b4b" }),
    brief: {
      header: "Floating rounded header (glass), gradient logo, pill CTA.",
      hero: "Gradient hero with headline, search bar, floating job cards preview.",
      signature: "Featured jobs as rounded cards with company avatars; stats as gradient tiles.",
      layout: "Rounded-xl, gradients, playful yet professional.",
      motion: "Fade-up sections.",
    },
    demo: { name: "HireHub", city: "Karachi" },
  },
  {
    id: "recruiting-04",
    category: "recruiting",
    name: "WorkForce PK",
    tagline: "Blue-collar, bold & simple",
    description: "Bold orange and charcoal, big buttons and simple copy for labour, drivers and skilled-trade recruitment.",
    style: ["bold", "simple", "blue-collar"],
    theme: theme({ primary: "#ea580c", primaryFg: "#fff", secondary: "#1f2937", accent: "#facc15", accentFg: "#1f2937", bg: "#ffffff", fg: "#1f2937", muted: "#fff7ed", mutedFg: "#6b7280", heading: "Oswald", body: "Roboto", radius: "sm", dark: "#1f2937" }),
    brief: {
      header: "Charcoal header, condensed uppercase nav, orange 'Apply now'.",
      hero: "Worker photo, condensed headline, 3 big buttons (Drivers, Labour, Technicians) → /jobs?q=.",
      signature: "Industries as big icon buttons; process with large numbers; WhatsApp CTA huge.",
      layout: "Large touch targets, high contrast, minimal text.",
    },
    demo: { name: "WorkForce PK", city: "Gujrat" },
  },
  {
    id: "recruiting-05",
    category: "recruiting",
    name: "MedStaff",
    tagline: "Healthcare recruitment, clean teal",
    description: "Clinical teal and white for nurses, doctors and medical staff placement (Gulf and UK).",
    style: ["healthcare", "clean", "teal"],
    theme: theme({ primary: "#0f766e", primaryFg: "#fff", secondary: "#134e4a", accent: "#38bdf8", accentFg: "#0c4a6e", bg: "#ffffff", fg: "#0f172a", muted: "#f0fdfa", mutedFg: "#5f7a76", heading: "Inter", body: "Inter", radius: "lg", dark: "#134e4a" }),
    brief: {
      header: "White header, teal cross-style logo mark, nav, 'Register as nurse' CTA.",
      hero: "Split hero with medical staff photo, headline, licence badges (DataFlow, Prometric, NMC).",
      signature: "Process section covers licensing steps; industries replaced by specialities chips.",
      layout: "Clean clinical, teal CTAs, rounded-lg.",
    },
    overrides: { hero: { eyebrow: { en: "Nurses · Doctors · Technicians", ur: "نرسیں · ڈاکٹرز · ٹیکنیشنز" }, title: { en: "Healthcare careers abroad, handled end to end", ur: "بیرونِ ملک ہیلتھ کیئر کیریئر، شروع سے آخر تک ہماری ذمہ داری" } }, industries: { title: { en: "Specialities we place", ur: "ہم جن شعبوں میں تعینات کرتے ہیں" }, items: [{ icon: "Stethoscope", title: { en: "Registered nurses", ur: "رجسٹرڈ نرسیں" }, href: "/jobs?q=nurse" }, { icon: "HeartPulse", title: { en: "Doctors & specialists", ur: "ڈاکٹرز اور اسپیشلسٹس" }, href: "/jobs?q=doctor" }, { icon: "Microscope", title: { en: "Lab technicians", ur: "لیب ٹیکنیشنز" }, href: "/jobs?q=lab" }, { icon: "Pill", title: { en: "Pharmacists", ur: "فارماسسٹس" }, href: "/jobs?q=pharmacist" }, { icon: "Activity", title: { en: "Physiotherapists", ur: "فزیوتھراپسٹس" }, href: "/jobs?q=physio" }, { icon: "Syringe", title: { en: "Paramedics", ur: "پیرامیڈیکس" }, href: "/jobs?q=paramedic" }] } },
    demo: { name: "MedStaff International", city: "Islamabad" },
  },
  {
    id: "recruiting-06",
    category: "recruiting",
    name: "Skyline Careers",
    tagline: "Dark premium executive search",
    description: "Dark charcoal with gold, serif headings and a discreet, executive-search tone for senior placements and headhunting.",
    style: ["dark", "executive", "premium"],
    theme: theme({ primary: "#c9a227", primaryFg: "#111111", secondary: "#f5f5f4", secondaryFg: "#111111", accent: "#e7e5e4", accentFg: "#111111", bg: "#121212", fg: "#f5f5f4", muted: "#1c1c1c", mutedFg: "#a8a29e", card: "#181818", border: "#2c2c2c", heading: "Playfair Display", body: "Inter", radius: "none", dark: "#0a0a0a" }),
    brief: {
      header: "Black header, gold serif logo, minimal nav.",
      hero: "Typographic hero, gold rule, single CTA 'Confidential enquiry'.",
      signature: "Featured jobs as understated list rows; team section prominent (consultants).",
      layout: "Dark, square corners, generous margins, gold hairlines.",
    },
    demo: { name: "Skyline Careers", city: "Karachi" },
  },
  {
    id: "recruiting-07",
    category: "recruiting",
    name: "Apna Rozgar",
    tagline: "Urdu-friendly, green & white, community",
    description: "Green-and-white Pakistan palette, large Urdu-friendly type and simple sections for local job placement and skills training centres.",
    style: ["local", "green", "accessible"],
    theme: theme({ primary: "#15803d", primaryFg: "#fff", secondary: "#14532d", accent: "#fbbf24", accentFg: "#14532d", bg: "#ffffff", fg: "#1f2937", muted: "#f0fdf4", mutedFg: "#4b5f52", heading: "Nunito", body: "Nunito", radius: "lg", dark: "#14532d" }),
    brief: {
      header: "Green header, crescent-inspired logo mark, big font sizes, language switch prominent.",
      hero: "Simple hero, big headline, two large buttons, phone number visible.",
      signature: "Industries as big colourful tiles; testimonials with photos.",
      layout: "Large type, high contrast, accessible spacing.",
    },
    defaultSettings: { languages: { urduEnabled: true, defaultLang: "ur" } },
    demo: { name: "Apna Rozgar Centre", city: "Sialkot" },
  },
  {
    id: "recruiting-08",
    category: "recruiting",
    name: "Crew Connect",
    tagline: "Hospitality & cruise staffing, coral",
    description: "Coral and navy with lively photography for hotel, restaurant and cruise-ship staffing agencies.",
    style: ["hospitality", "lively", "coral"],
    theme: theme({ primary: "#f43f5e", primaryFg: "#fff", secondary: "#0f172a", accent: "#0ea5e9", accentFg: "#fff", bg: "#ffffff", fg: "#0f172a", muted: "#fff1f2", mutedFg: "#64748b", heading: "Outfit", body: "Outfit", radius: "xl", dark: "#0f172a" }),
    brief: {
      header: "White header, coral logo, rounded nav, 'Apply' pill.",
      hero: "Collage of hospitality photos, headline, search bar.",
      signature: "Industries as photo tiles (Hotels, Cruise, Restaurants, Airlines); stats in coral.",
      layout: "Rounded, lively, photo-rich.",
    },
    demo: { name: "Crew Connect", city: "Lahore" },
  },
  {
    id: "recruiting-09",
    category: "recruiting",
    name: "TechTalent",
    tagline: "IT recruiting, monospace accents",
    description: "Dark-blue and electric green with monospace accents for IT and remote-job recruiting agencies.",
    style: ["tech", "dark-blue", "mono"],
    theme: theme({ primary: "#22c55e", primaryFg: "#052e16", secondary: "#e2e8f0", secondaryFg: "#0b1220", accent: "#38bdf8", accentFg: "#0b1220", bg: "#0b1220", fg: "#e2e8f0", muted: "#111a2e", mutedFg: "#94a3b8", card: "#0f172a", border: "#1e293b", heading: "Space Grotesk", body: "Inter", radius: "md", dark: "#060b16" }),
    brief: {
      header: "Dark header, green terminal-style logo '>_', nav.",
      hero: "Code-window styled card with typed headline effect (CSS), search bar.",
      signature: "Jobs as cards with tech-stack chips in monospace; process as pipeline.",
      layout: "Dark tech, green accents, mono labels.",
    },
    demo: { name: "TechTalent", city: "Islamabad" },
  },
  {
    id: "recruiting-10",
    category: "recruiting",
    name: "Bridgeway",
    tagline: "Warm, human, photo-led",
    description: "Warm beige and terracotta with big people photography and rounded cards, emphasising trust and family stories.",
    style: ["warm", "human", "photo"],
    theme: theme({ primary: "#c2410c", primaryFg: "#fff", secondary: "#292524", accent: "#fde68a", accentFg: "#292524", bg: "#fdfaf6", fg: "#292524", muted: "#f5efe6", mutedFg: "#78716c", border: "#eadfd1", heading: "Lora", body: "Nunito Sans", radius: "xl", dark: "#292524" }),
    brief: {
      header: "Beige header, serif logo, nav, terracotta CTA.",
      hero: "Large portrait photo with quote overlay, headline, CTAs.",
      signature: "Testimonials as story cards with photos; team section warm.",
      layout: "Warm rounded, serif headings, human tone.",
    },
    demo: { name: "Bridgeway Overseas", city: "Faisalabad" },
  },
];
