import { theme, type Blueprint } from "@/templates/catalog/index";

/** 15 restaurant-type templates: pizza 10 · bakery 5 */
export const restaurantBlueprints: Blueprint[] = [
  /* ───────── PIZZA (10) ───────── */
  {
    id: "pizza-01",
    category: "pizza",
    name: "Slice House",
    tagline: "Classic red & cream pizzeria",
    description: "Warm Italian-American pizzeria feel: red accents, cream background, checkered details and a deals-first home page.",
    style: ["classic", "warm", "family"],
    theme: theme({ primary: "#c62828", primaryFg: "#fff", secondary: "#1f1a17", accent: "#f2b134", accentFg: "#1f1a17", bg: "#fffaf3", fg: "#1f1a17", muted: "#f8efe2", mutedFg: "#7a6a5a", border: "#eadfce", heading: "Lobster", body: "Nunito", radius: "lg", dark: "#1f1a17" }),
    brief: {
      header: "Cream header, red script logo, nav, 'Order now' red pill; open-now badge next to phone.",
      hero: "Big pizza photo on right, headline in Lobster, deals badge floating; checkered red strip under hero.",
      signature: "Deals as red ticket-style cards with dashed edges; featured menu grid with 'Add' buttons.",
      layout: "Warm cream, red CTAs, rounded cards, dark footer with hours.",
    },
    demo: { name: "Slice House", city: "Lahore" },
  },
  {
    id: "pizza-02",
    category: "pizza",
    name: "Brick Oven",
    tagline: "Artisan wood-fired, dark & rustic",
    description: "Dark charcoal and ember tones with wood textures, serif type and photography-led sections for artisan wood-fired pizzerias.",
    style: ["dark", "artisan", "rustic"],
    theme: theme({ primary: "#e07a1f", primaryFg: "#1a1512", secondary: "#f3e9dc", secondaryFg: "#1a1512", accent: "#b91c1c", accentFg: "#fff", bg: "#1a1512", fg: "#f3e9dc", muted: "#241d18", mutedFg: "#b3a595", card: "#221b16", border: "#3a2f27", heading: "Playfair Display", body: "Lato", radius: "sm", dark: "#110d0b" }),
    brief: {
      header: "Transparent over hero, serif logo, ember-orange CTA; solid dark on scroll.",
      hero: "Full-screen oven-fire photo with dark gradient, serif headline, 'Order online' + 'View menu'.",
      signature: "Featured menu as large image cards with price on ember badge; about section with 'wood-fired since' timeline.",
      layout: "Dark rustic, ember accents, serif headings, subtle grain.",
    },
    demo: { name: "Brick Oven Pizzeria", city: "Islamabad" },
  },
  {
    id: "pizza-03",
    category: "pizza",
    name: "PizzaGo",
    tagline: "Fast-delivery app style",
    description: "Bright orange delivery-app layout with sticky order bar, 30-minute promise and zone-based delivery emphasis.",
    style: ["app-like", "fast", "bright"],
    theme: theme({ primary: "#ff6b00", primaryFg: "#fff", secondary: "#1f2937", accent: "#16a34a", accentFg: "#fff", bg: "#ffffff", fg: "#1f2937", muted: "#fff4ea", mutedFg: "#6b7280", heading: "Poppins", body: "Poppins", radius: "xl", dark: "#1f2937" }),
    brief: {
      header: "Orange header with location chip 'Deliver to: Gulberg', logo, cart pill.",
      hero: "Search/quick-order card over an orange gradient, ETA badge '30 min', deal chips.",
      signature: "Delivery areas as a chip cloud with fees; process as 3 app-style steps.",
      layout: "Mobile-first, card UI, orange CTAs, sticky cart bar always visible.",
    },
    demo: { name: "PizzaGo", city: "Karachi" },
  },
  {
    id: "pizza-04",
    category: "pizza",
    name: "Napoli Verde",
    tagline: "Fresh Italian green & white",
    description: "Basil green, tomato red and white with a Neapolitan menu aesthetic for authentic Italian pizza restaurants.",
    style: ["italian", "fresh", "elegant"],
    theme: theme({ primary: "#2e7d32", primaryFg: "#fff", secondary: "#1b5e20", accent: "#d32f2f", accentFg: "#fff", bg: "#ffffff", fg: "#1f2a1f", muted: "#f1f8f1", mutedFg: "#5f6f5f", heading: "Cormorant Garamond", body: "Montserrat", radius: "md", dark: "#1b5e20" }),
    brief: {
      header: "White header, tricolour hairline (green/white/red) at top, serif logo, nav.",
      hero: "Ingredient photo left, serif headline right, 'Menu' and 'Reserve a table' buttons.",
      signature: "Menu preview styled as a printed menu (dotted leaders between name and price); gallery as film strip.",
      layout: "Elegant serif, tricolour accents, white space.",
    },
    defaultSettings: { restaurant: { acceptingOrders: true, delivery: true, pickup: true, dineIn: true, reservations: true, minDeliveryOrder: 800, defaultDeliveryFee: 150, prepTimeMins: 35, soundAlerts: true } },
    demo: { name: "Napoli Verde", city: "Lahore" },
  },
  {
    id: "pizza-05",
    category: "pizza",
    name: "Midnight Slice",
    tagline: "Late-night neon pizza",
    description: "Black and neon pink/purple for late-night pizza joints and student deals with a bold marquee ticker.",
    style: ["neon", "night", "youth"],
    theme: theme({ primary: "#ff2d95", primaryFg: "#0b0b0f", secondary: "#f5f5f5", secondaryFg: "#0b0b0f", accent: "#7c3aed", accentFg: "#fff", bg: "#0b0b0f", fg: "#f5f5f5", muted: "#15151d", mutedFg: "#a1a1aa", card: "#12121a", border: "#26262f", heading: "Bangers", body: "Inter", radius: "md", dark: "#050507" }),
    brief: {
      header: "Black header, neon pink logo, 'Open till 3AM' badge.",
      hero: "Neon-outlined pizza image, comic-style headline, marquee ticker of deals.",
      signature: "Deals as neon-bordered cards; hours block highlights late night.",
      layout: "Dark neon, bold type, ticker motion.",
      motion: "Marquee ticker; neon glow hover.",
    },
    overrides: { hero: { eyebrow: { en: "Open till 3 AM", ur: "رات 3 بجے تک کھلا" }, title: { en: "Late night? Pizza night.", ur: "رات دیر تک؟ پیزا نائٹ!" } } },
    demo: { name: "Midnight Slice", city: "Lahore" },
  },
  {
    id: "pizza-06",
    category: "pizza",
    name: "Family Feast",
    tagline: "Big deals, family combos",
    description: "Friendly blue and yellow layout centred on family combos, party deals and bulk orders for occasions.",
    style: ["family", "deals", "friendly"],
    theme: theme({ primary: "#1d4ed8", primaryFg: "#fff", secondary: "#1e3a8a", accent: "#fbbf24", accentFg: "#1e3a8a", bg: "#ffffff", fg: "#1e293b", muted: "#eff6ff", mutedFg: "#64748b", heading: "Fredoka", body: "Nunito", radius: "xl", dark: "#1e3a8a" }),
    brief: {
      header: "Blue header, rounded yellow order button, phone with icon.",
      hero: "Combo image collage, headline 'Feed the whole family', big price badge.",
      signature: "Deals as large horizontal cards with 'Serves 4-6' chips; party orders CTA in banner style.",
      layout: "Rounded, friendly, blue/yellow.",
    },
    demo: { name: "Family Feast Pizza", city: "Faisalabad" },
  },
  {
    id: "pizza-07",
    category: "pizza",
    name: "Crust & Co.",
    tagline: "Minimal monochrome, premium",
    description: "Black-and-white minimal layout with one accent colour, big typography and a curated menu for premium pizza bars.",
    style: ["minimal", "monochrome", "premium"],
    theme: theme({ primary: "#111111", primaryFg: "#fff", secondary: "#111111", accent: "#e63946", accentFg: "#fff", bg: "#ffffff", fg: "#111111", muted: "#f5f5f5", mutedFg: "#6b6b6b", heading: "Syne", body: "Inter", radius: "none", dark: "#111111" }),
    brief: {
      header: "White header, black wordmark, tiny nav, black 'Order' button.",
      hero: "Massive typographic headline (Syne), small image, one red accent word.",
      signature: "Menu preview as a stark list with prices right-aligned; gallery as 3 large squares.",
      layout: "Square corners, black/white, red accent sparingly.",
    },
    demo: { name: "Crust & Co.", city: "Karachi" },
  },
  {
    id: "pizza-08",
    category: "pizza",
    name: "Desi Tandoor Pizza",
    tagline: "Desi flavours, spicy & vibrant",
    description: "Saffron, chilli-red and green with truck-art inspired accents for tikka/tandoori pizza brands.",
    style: ["desi", "vibrant", "spicy"],
    theme: theme({ primary: "#e65100", primaryFg: "#fff", secondary: "#1b5e20", accent: "#fdd835", accentFg: "#1f1f1f", bg: "#fffdf7", fg: "#1f1f1f", muted: "#fff3e0", mutedFg: "#7a5c3a", heading: "Righteous", body: "Poppins", radius: "lg", dark: "#3e1a00" }),
    brief: {
      header: "Saffron header with pattern border (CSS repeating gradient), bold logo, green order button.",
      hero: "Spicy tikka pizza photo, headline with chilli icon, 'Spice level' chips.",
      signature: "Deals as truck-art style cards with bright borders; testimonials with Urdu-friendly type.",
      layout: "Vibrant colours, pattern borders, rounded cards.",
    },
    overrides: { hero: { eyebrow: { en: "Tikka · Tandoori · Malai Boti", ur: "تکہ · تندوری · ملائی بوٹی" }, title: { en: "Desi flavours on a pizza", ur: "پیزا پر دیسی ذائقے" } } },
    demo: { name: "Desi Tandoor Pizza", city: "Rawalpindi" },
  },
  {
    id: "pizza-09",
    category: "pizza",
    name: "Slice Republic",
    tagline: "Modern chain look, multi-branch",
    description: "Clean corporate chain look with red and charcoal, branch locator block and consistent grid for multi-outlet brands.",
    style: ["chain", "modern", "consistent"],
    theme: theme({ primary: "#d62828", primaryFg: "#fff", secondary: "#2b2d42", accent: "#f77f00", accentFg: "#fff", bg: "#ffffff", fg: "#2b2d42", muted: "#f4f4f6", mutedFg: "#6b6e85", heading: "Montserrat", body: "Montserrat", radius: "md", dark: "#2b2d42" }),
    brief: {
      header: "White header with red top bar (phone, hours), logo, nav, order button.",
      hero: "Slider hero with 2 slides, branch/hours strip beneath.",
      signature: "Delivery areas block as branch cards; features as 4 icon tiles.",
      layout: "Corporate grid, red/charcoal, consistent card sizes.",
    },
    demo: { name: "Slice Republic", city: "Islamabad" },
  },
  {
    id: "pizza-10",
    category: "pizza",
    name: "Cheesy Cartoon",
    tagline: "Playful cartoon kids-friendly",
    description: "Cartoonish yellow and red, rounded everything, mascot-friendly layout for family pizza places and kids' parties.",
    style: ["cartoon", "playful", "kids"],
    theme: theme({ primary: "#f4b400", primaryFg: "#1f1f1f", secondary: "#d32f2f", accent: "#d32f2f", accentFg: "#fff", bg: "#fffef5", fg: "#1f1f1f", muted: "#fff7d6", mutedFg: "#7a6a2a", heading: "Luckiest Guy", body: "Nunito", radius: "full", dark: "#3b1b1b" }),
    brief: {
      header: "Yellow bubbly header, chunky logo, red pill nav.",
      hero: "Cartoon-style hero with wobbly shapes (CSS border-radius blobs), big fun headline.",
      signature: "Deals as 'coupon' cards with scissors icon; process as bubbles.",
      layout: "Fully rounded, bright, fun; kids' party CTA.",
    },
    overrides: { cta: { title: { en: "Kids' party at our place?", ur: "بچوں کی پارٹی ہمارے ہاں؟" }, text: { en: "Pizza-making parties for birthdays. Book a slot, we handle the mess.", ur: "سالگرہ کے لیے پیزا بنانے کی پارٹیاں۔ وقت بک کریں، صفائی ہم پر چھوڑ دیں۔" }, cta: { label: { en: "Book a party", ur: "پارٹی بک کریں" }, href: "/contact" } } },
    demo: { name: "Cheesy Cartoon Pizza", city: "Lahore" },
  },

  /* ───────── BAKERY (5) ───────── */
  {
    id: "bakery-01",
    category: "bakery",
    name: "Sugar & Flour",
    tagline: "Pastel patisserie, elegant",
    description: "Blush pastel patisserie look with script accents, cake-first imagery and custom cake ordering.",
    style: ["pastel", "elegant", "patisserie"],
    theme: theme({ primary: "#c2185b", primaryFg: "#fff", secondary: "#4a1a2c", accent: "#f8bbd0", accentFg: "#4a1a2c", bg: "#fff8fa", fg: "#3d1f2b", muted: "#fdeef3", mutedFg: "#8a6a75", border: "#f6d5e0", heading: "Pacifico", body: "Quicksand", radius: "xl", dark: "#4a1a2c" }),
    brief: {
      header: "Soft pink header, script logo, rounded nav, 'Order cake' button.",
      hero: "Cake photo in circular frame, script eyebrow, headline, two CTAs.",
      signature: "Custom cake section as a pastel card with occasion icons; featured menu as round-image cards.",
      layout: "Pastel, rounded, script accents, scalloped section edges (CSS radial).",
    },
    demo: { name: "Sugar & Flour", city: "Lahore" },
  },
  {
    id: "bakery-02",
    category: "bakery",
    name: "Daily Crust",
    tagline: "Rustic artisan bread bakery",
    description: "Wheat and walnut tones, kraft-paper textures and serif type for sourdough, bread and savoury bakeries.",
    style: ["rustic", "artisan", "bread"],
    theme: theme({ primary: "#8b5e34", primaryFg: "#fff", secondary: "#3e2a1a", accent: "#d9a441", accentFg: "#3e2a1a", bg: "#f9f4ec", fg: "#3e2a1a", muted: "#f1e8da", mutedFg: "#7d6a55", border: "#e6d9c5", heading: "Lora", body: "Source Sans 3", radius: "sm", dark: "#3e2a1a" }),
    brief: {
      header: "Kraft-toned header, serif logo with wheat icon, nav.",
      hero: "Bread photo left, headline right, 'Baked at 6am daily' badge, opening hours chip.",
      signature: "Featured menu as a chalkboard-style list; hours block prominent.",
      layout: "Warm kraft paper, serif, subtle texture.",
    },
    demo: { name: "Daily Crust Bakery", city: "Islamabad" },
  },
  {
    id: "bakery-03",
    category: "bakery",
    name: "Cake Studio",
    tagline: "Bold modern custom cakes",
    description: "Bold black, white and hot pink with big photography for designer cakes, cupcakes and custom orders.",
    style: ["bold", "modern", "designer"],
    theme: theme({ primary: "#ff1f8f", primaryFg: "#fff", secondary: "#111111", accent: "#111111", accentFg: "#fff", bg: "#ffffff", fg: "#111111", muted: "#fff0f7", mutedFg: "#6b6b6b", heading: "Outfit", body: "Outfit", radius: "lg", dark: "#111111" }),
    brief: {
      header: "White header, bold black logo, pink 'Order custom cake'.",
      hero: "Large cake photo grid (3 images), bold headline, pink CTA.",
      signature: "Custom cake form emphasised as the main CTA; gallery masonry of cakes.",
      layout: "Bold contrast, pink accents, photography-first.",
    },
    demo: { name: "Cake Studio", city: "Karachi" },
  },
  {
    id: "bakery-04",
    category: "bakery",
    name: "Mithai & More",
    tagline: "Desi sweets & bakery, festive",
    description: "Festive maroon and gold for mithai shops and bakeries with Eid/wedding gifting and bulk orders.",
    style: ["festive", "desi", "gold"],
    theme: theme({ primary: "#8e0e2a", primaryFg: "#fff", secondary: "#3b0713", accent: "#d4a017", accentFg: "#3b0713", bg: "#fffcf7", fg: "#2d1a1f", muted: "#fbf1e6", mutedFg: "#7d5a62", border: "#f0ddd0", heading: "Marcellus", body: "Lato", radius: "md", dark: "#3b0713" }),
    brief: {
      header: "Maroon header with gold logotype and gold hairline.",
      hero: "Mithai box photo, gold ornament dividers, 'Eid & wedding orders' badge.",
      signature: "Custom cake section repurposed as 'Bulk & gift orders'; gallery in gold frames.",
      layout: "Festive maroon/gold, ornamental dividers.",
    },
    overrides: { hero: { eyebrow: { en: "Mithai · Cakes · Bakery", ur: "مٹھائی · کیک · بیکری" }, title: { en: "Sweetness for every celebration", ur: "ہر خوشی کے لیے مٹھاس" } }, customCake: { title: { en: "Bulk orders for Eid, weddings & events", ur: "عید، شادیوں اور تقریبات کے لیے بلک آرڈرز" }, text: { en: "Mithai boxes, cake towers and dessert tables for 50 to 5,000 guests. Order 3 days in advance.", ur: "50 سے 5,000 مہمانوں کے لیے مٹھائی کے ڈبے، کیک ٹاورز اور ڈیزرٹ ٹیبلز۔ 3 دن پہلے آرڈر کریں۔" }, cta: { label: { en: "Request bulk order", ur: "بلک آرڈر کی درخواست" }, href: "/custom-cake" } } },
    demo: { name: "Mithai & More", city: "Multan" },
  },
  {
    id: "bakery-05",
    category: "bakery",
    name: "Morning Bun",
    tagline: "Cafe-bakery, cozy and minimal",
    description: "Cozy cafe-bakery with sage and cream, coffee pairing, minimal type and pickup-first ordering.",
    style: ["cozy", "cafe", "minimal"],
    theme: theme({ primary: "#4f6f52", primaryFg: "#fff", secondary: "#2f3e30", accent: "#e8c07d", accentFg: "#2f3e30", bg: "#fbfaf6", fg: "#2f3e30", muted: "#f0efe8", mutedFg: "#6f776f", border: "#e3e2d8", heading: "DM Serif Display", body: "DM Sans", radius: "lg", dark: "#2f3e30" }),
    brief: {
      header: "Cream header, serif logo, sage nav, 'Order for pickup'.",
      hero: "Cozy cafe photo, serif headline, 'Order ahead, skip the queue' CTA.",
      signature: "Featured menu as coffee-pairing cards; hours and location block styled as a cafe sign.",
      layout: "Minimal, cozy, sage/cream.",
    },
    defaultSettings: { restaurant: { acceptingOrders: true, delivery: true, pickup: true, dineIn: true, reservations: false, minDeliveryOrder: 600, defaultDeliveryFee: 120, prepTimeMins: 20, soundAlerts: true } },
    demo: { name: "Morning Bun", city: "Islamabad" },
  },
];
