import { theme, type Blueprint } from "@/templates/catalog/index";

/** 18 service-type templates: realestate 3 · gym 5 · law 6 · printing 4 */
export const serviceBlueprints: Blueprint[] = [
  /* ───────── REAL ESTATE (3) ───────── */
  {
    id: "realestate-01",
    category: "realestate",
    name: "Estate Prime",
    tagline: "Classic navy & gold property agency",
    description: "Trust-first navy and gold with a property search hero, featured listings grid and area tiles for established agencies.",
    style: ["classic", "trust", "navy"],
    theme: theme({ primary: "#1e3a8a", primaryFg: "#fff", secondary: "#0f172a", accent: "#d4af37", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "Playfair Display", body: "Inter", radius: "md", dark: "#0f172a" }),
    brief: {
      header: "White header, navy serif logo, nav, gold 'List your property'.",
      hero: "Skyline/house photo with PropertySearch bar card (purpose, type, city, price).",
      signature: "Featured properties grid with purpose badges; areas as photo tiles; agents row.",
      layout: "Classic grid, navy/gold, serif headings.",
    },
    demo: { name: "Estate Prime", city: "Lahore" },
  },
  {
    id: "realestate-02",
    category: "realestate",
    name: "Urban Nest",
    tagline: "Modern minimal, apartments & rentals",
    description: "Minimal black-and-white with a single accent, map-like feel and card grid for apartments, rentals and city living.",
    style: ["minimal", "modern", "rental"],
    theme: theme({ primary: "#111827", primaryFg: "#fff", secondary: "#111827", accent: "#10b981", accentFg: "#052e16", bg: "#ffffff", fg: "#111827", muted: "#f9fafb", mutedFg: "#6b7280", heading: "Manrope", body: "Manrope", radius: "lg", dark: "#111827" }),
    brief: {
      header: "Minimal header, wordmark, search icon, 'Rent' / 'Buy' toggle in nav.",
      hero: "Search-first hero (large search bar centred), headline small, key stats.",
      signature: "Property cards with large photos and minimal meta; areas as text list with counts.",
      layout: "Minimal, rounded-lg cards, green accent.",
    },
    overrides: { hero: { eyebrow: "Apartments · Houses · Offices", title: { en: "Find a place you'll love to live" } } },
    demo: { name: "Urban Nest Realty", city: "Karachi" },
  },
  {
    id: "realestate-03",
    category: "realestate",
    name: "Plot Point",
    tagline: "Plots & investment, green & earth",
    description: "Earthy green and sand for plot dealers and investment advisors in Bahria Town, DHA and new housing societies.",
    style: ["investment", "earthy", "plots"],
    theme: theme({ primary: "#15803d", primaryFg: "#fff", secondary: "#14532d", accent: "#d97706", accentFg: "#fff", bg: "#fbfaf6", fg: "#1c1917", muted: "#f0f4ee", mutedFg: "#5f6b5a", border: "#e2e6dc", heading: "Sora", body: "Inter", radius: "sm", dark: "#14532d" }),
    brief: {
      header: "Green header, logo, nav, WhatsApp button.",
      hero: "Map-style background (CSS grid lines), headline about investment, society chips.",
      signature: "Areas as society cards with 'from Rs' notes; stats emphasised (ROI, plots sold); process for transfer.",
      layout: "Grid motifs, green/amber, data-forward.",
    },
    overrides: { hero: { eyebrow: "Plots · Files · Investment", title: { en: "Invest in Pakistan's fastest-growing societies" } } },
    demo: { name: "Plot Point Advisors", city: "Islamabad" },
  },

  /* ───────── GYM (5) ───────── */
  {
    id: "gym-01",
    category: "gym",
    name: "IronPulse",
    tagline: "Dark, aggressive, red",
    description: "Black and red high-intensity look with big condensed type, plans and timetable for strength gyms.",
    style: ["dark", "intense", "red"],
    theme: theme({ primary: "#ef4444", primaryFg: "#fff", secondary: "#f5f5f5", secondaryFg: "#0a0a0a", accent: "#fbbf24", accentFg: "#0a0a0a", bg: "#0a0a0a", fg: "#f5f5f5", muted: "#161616", mutedFg: "#a3a3a3", card: "#121212", border: "#262626", heading: "Anton", body: "Inter", radius: "sm", dark: "#000000" }),
    brief: {
      header: "Black header, Anton logo, red 'Join now'.",
      hero: "Dark gym photo, huge headline, red diagonal accent, stats row.",
      signature: "Plans as dark cards with red popular badge; timetable in dark table; transformations gallery.",
      layout: "Dark, sharp, red accents, big type.",
    },
    demo: { name: "IronPulse Gym", city: "Lahore" },
  },
  {
    id: "gym-02",
    category: "gym",
    name: "FitFam",
    tagline: "Friendly community, teal & coral",
    description: "Bright teal and coral, rounded and welcoming for family gyms with ladies sections and group classes.",
    style: ["friendly", "community", "bright"],
    theme: theme({ primary: "#0d9488", primaryFg: "#fff", secondary: "#134e4a", accent: "#fb7185", accentFg: "#fff", bg: "#ffffff", fg: "#1f2937", muted: "#f0fdfa", mutedFg: "#5b6b6a", heading: "Outfit", body: "Nunito", radius: "xl", dark: "#134e4a" }),
    brief: {
      header: "White header, teal logo, rounded nav, coral 'Free trial'.",
      hero: "Rounded photo collage, friendly headline, 'Ladies timings' badge.",
      signature: "Classes timetable with colour-coded chips; trainers as circle cards; BMI calculator card.",
      layout: "Rounded, bright, friendly.",
    },
    demo: { name: "FitFam Family Gym", city: "Rawalpindi" },
  },
  {
    id: "gym-03",
    category: "gym",
    name: "Zen Studio",
    tagline: "Yoga & pilates, calm sage",
    description: "Calm sage and cream, serif type and soft imagery for yoga, pilates and wellness studios.",
    style: ["calm", "wellness", "serif"],
    theme: theme({ primary: "#4f6f52", primaryFg: "#fff", secondary: "#2f3e30", accent: "#e8c07d", accentFg: "#2f3e30", bg: "#fbfaf6", fg: "#2f3e30", muted: "#f0efe8", mutedFg: "#6f776f", border: "#e3e2d8", heading: "Cormorant Garamond", body: "DM Sans", radius: "lg", dark: "#2f3e30" }),
    brief: {
      header: "Cream header, serif logo, minimal nav.",
      hero: "Soft photo, serif headline, single CTA 'Book a class'.",
      signature: "Classes as a calm weekly list; plans as minimal cards; testimonials as quotes.",
      layout: "Calm, spacious, serif, sage.",
    },
    overrides: { hero: { eyebrow: "Yoga · Pilates · Meditation", title: { en: "Move gently. Breathe deeply." } } },
    demo: { name: "Zen Studio", city: "Islamabad" },
  },
  {
    id: "gym-04",
    category: "gym",
    name: "CrossBox",
    tagline: "CrossFit & HIIT, industrial",
    description: "Industrial concrete grey with safety-yellow accents and stencil type for CrossFit boxes and HIIT studios.",
    style: ["industrial", "yellow", "stencil"],
    theme: theme({ primary: "#facc15", primaryFg: "#111111", secondary: "#111111", accent: "#111111", accentFg: "#fff", bg: "#f4f4f4", fg: "#111111", muted: "#e5e5e5", mutedFg: "#525252", card: "#ffffff", border: "#d4d4d4", heading: "Bebas Neue", body: "Barlow", radius: "none", dark: "#111111" }),
    brief: {
      header: "Black header, yellow stencil logo, uppercase nav.",
      hero: "Concrete texture background (CSS), giant headline, yellow tape stripe.",
      signature: "WOD-style class timetable; plans as ticket cards; stats with big numbers.",
      layout: "Industrial, square corners, yellow/black stripes.",
    },
    demo: { name: "CrossBox", city: "Karachi" },
  },
  {
    id: "gym-05",
    category: "gym",
    name: "Ladies Fit",
    tagline: "Women-only fitness, plum & blush",
    description: "Plum and blush, elegant yet energetic for women-only gyms and ladies fitness centres.",
    style: ["women", "elegant", "plum"],
    theme: theme({ primary: "#9d174d", primaryFg: "#fff", secondary: "#4a044e", accent: "#fbcfe8", accentFg: "#4a044e", bg: "#fff8fa", fg: "#3b1f2b", muted: "#fdeef4", mutedFg: "#8a6b78", border: "#f7d6e3", heading: "Poppins", body: "Poppins", radius: "xl", dark: "#4a044e" }),
    brief: {
      header: "Blush header, plum logo, rounded nav, 'Join today'.",
      hero: "Photo of ladies class, headline, 'Privacy guaranteed' badge.",
      signature: "Plans with 'Ladies only' framing; classes (Zumba, yoga, aerobics); transformations gallery.",
      layout: "Rounded, plum/blush, energetic.",
    },
    overrides: { hero: { eyebrow: "Women-only gym", title: { en: "Your space. Your strength." } } },
    demo: { name: "Ladies Fit", city: "Lahore" },
  },

  /* ───────── LAW (6) ───────── */
  {
    id: "law-01",
    category: "law",
    name: "Lex Chambers",
    tagline: "Classic navy & gold chambers",
    description: "Traditional law-firm look: navy, gold, serif headings, practice areas grid and attorney profiles.",
    style: ["classic", "navy", "serif"],
    theme: theme({ primary: "#1e3a8a", primaryFg: "#fff", secondary: "#0f172a", accent: "#c9a227", accentFg: "#0f172a", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "Libre Baskerville", body: "Source Sans 3", radius: "none", dark: "#0f172a" }),
    brief: {
      header: "White header, serif logo with scales icon, nav, gold 'Consultation'.",
      hero: "Split hero with courthouse/office photo, serif headline, two CTAs.",
      signature: "Practice areas as icon cards with gold hairlines; attorneys grid; case results stats.",
      layout: "Formal, square corners, navy/gold.",
    },
    demo: { name: "Lex Chambers", city: "Lahore" },
  },
  {
    id: "law-02",
    category: "law",
    name: "Advocate Modern",
    tagline: "Modern minimal, black & white",
    description: "Contemporary minimal firm site with black/white, large type and one accent for boutique corporate law practices.",
    style: ["modern", "minimal", "corporate"],
    theme: theme({ primary: "#111111", primaryFg: "#fff", secondary: "#111111", accent: "#2563eb", accentFg: "#fff", bg: "#ffffff", fg: "#111111", muted: "#f5f5f5", mutedFg: "#6b6b6b", heading: "Syne", body: "Inter", radius: "sm", dark: "#111111" }),
    brief: {
      header: "Minimal header, wordmark, small nav, black CTA.",
      hero: "Typographic hero with large headline and short intro; blue accent line.",
      signature: "Practice areas as numbered list; attorneys as wide cards.",
      layout: "Minimal, generous whitespace, black/white/blue.",
    },
    demo: { name: "Advocate Modern", city: "Karachi" },
  },
  {
    id: "law-03",
    category: "law",
    name: "Family Counsel",
    tagline: "Warm, approachable, family law",
    description: "Warm terracotta and cream, rounded cards and approachable tone for family law, inheritance and property disputes.",
    style: ["warm", "approachable", "family"],
    theme: theme({ primary: "#b45309", primaryFg: "#fff", secondary: "#292524", accent: "#fde68a", accentFg: "#292524", bg: "#fffaf5", fg: "#292524", muted: "#f5ebe0", mutedFg: "#78716c", border: "#eaddcf", heading: "Lora", body: "Nunito Sans", radius: "lg", dark: "#292524" }),
    brief: {
      header: "Cream header, serif logo, nav, terracotta CTA.",
      hero: "Portrait photo, warm headline, 'Confidential first consultation' badge.",
      signature: "Practice areas with plain-language descriptions; FAQ prominent; team warm.",
      layout: "Rounded, warm, readable.",
    },
    overrides: { hero: { eyebrow: "Family · Inheritance · Property", title: { en: "Legal help, explained in plain language" } } },
    demo: { name: "Family Counsel Associates", city: "Multan" },
  },
  {
    id: "law-04",
    category: "law",
    name: "Corporate Counsel",
    tagline: "Corporate & tax, slate & teal",
    description: "Slate and teal, data-forward layout for corporate, tax and compliance advisory firms.",
    style: ["corporate", "slate", "teal"],
    theme: theme({ primary: "#0f766e", primaryFg: "#fff", secondary: "#1e293b", accent: "#38bdf8", accentFg: "#0c4a6e", bg: "#ffffff", fg: "#1e293b", muted: "#f1f5f9", mutedFg: "#64748b", heading: "IBM Plex Sans", body: "IBM Plex Sans", radius: "sm", dark: "#1e293b" }),
    brief: {
      header: "Slate header, teal logo, nav, 'Book advisory call'.",
      hero: "Split hero with abstract office photo, headline, stats.",
      signature: "Practice areas as table-like cards; process as compliance steps; brands/clients strip via features.",
      layout: "Formal grid, slate/teal.",
    },
    overrides: { hero: { eyebrow: "Corporate · Tax · Compliance", title: { en: "Counsel that keeps your business compliant" } } },
    demo: { name: "Corporate Counsel LLP", city: "Islamabad" },
  },
  {
    id: "law-05",
    category: "law",
    name: "Justice Dark",
    tagline: "Dark premium litigation",
    description: "Dark charcoal with gold, dramatic photography and serif type for litigation-focused firms.",
    style: ["dark", "premium", "litigation"],
    theme: theme({ primary: "#c9a227", primaryFg: "#111111", secondary: "#f5f5f4", secondaryFg: "#111111", accent: "#e7e5e4", accentFg: "#111111", bg: "#121212", fg: "#f5f5f4", muted: "#1c1c1c", mutedFg: "#a8a29e", card: "#181818", border: "#2c2c2c", heading: "Cinzel", body: "Inter", radius: "none", dark: "#0a0a0a" }),
    brief: {
      header: "Black header, gold Cinzel logo, minimal nav.",
      hero: "Dark courtroom photo, gold headline, single CTA.",
      signature: "Case results stats in gold; attorneys in dark cards; practice areas list with gold numerals.",
      layout: "Dark, square, gold hairlines.",
    },
    demo: { name: "Justice Chambers", city: "Lahore" },
  },
  {
    id: "law-06",
    category: "law",
    name: "Solo Advocate",
    tagline: "Personal brand, single lawyer",
    description: "Personal-brand layout for a single advocate: big portrait hero, credentials, practice areas and consultation booking.",
    style: ["personal", "portrait", "clean"],
    theme: theme({ primary: "#7f1d1d", primaryFg: "#fff", secondary: "#1c1917", accent: "#d6d3d1", accentFg: "#1c1917", bg: "#fafaf9", fg: "#1c1917", muted: "#f0efed", mutedFg: "#6b6560", border: "#e5e2df", heading: "EB Garamond", body: "Work Sans", radius: "md", dark: "#1c1917" }),
    brief: {
      header: "Simple header with advocate's name as logo, nav, phone.",
      hero: "Large portrait left, name + credentials right (Advocate High Court), CTAs.",
      signature: "About block as credentials timeline; practice areas compact; testimonials.",
      layout: "Personal, clean, maroon accent.",
    },
    overrides: { hero: { eyebrow: "Advocate High Court", title: { en: "Personal attention to every case" } }, team: { title: { en: "About the advocate" } } },
    demo: { name: "Adv. Ahmed Raza Chambers", city: "Faisalabad" },
  },

  /* ───────── PRINTING (4) ───────── */
  {
    id: "printing-01",
    category: "printing",
    name: "PrintPress",
    tagline: "CMYK bold, services-first",
    description: "Bold CMYK-inspired palette with services grid, price-from tags and a quote form for digital and offset printers.",
    style: ["bold", "cmyk", "retail"],
    theme: theme({ primary: "#0891b2", primaryFg: "#fff", secondary: "#111827", accent: "#ec4899", accentFg: "#fff", bg: "#ffffff", fg: "#111827", muted: "#f3f4f6", mutedFg: "#6b7280", heading: "Poppins", body: "Inter", radius: "md", dark: "#111827" }),
    brief: {
      header: "White header with CMYK colour bar on top, logo, nav, 'Get a quote' pink.",
      hero: "Split hero with print samples collage, headline, upload CTA.",
      signature: "Services grid with 'From Rs' tags; process with upload/approve/print icons; portfolio masonry.",
      layout: "Bold colour accents, grid, CMYK motifs.",
    },
    features: ["Services grid with 'From Rs' tags", "Upload / approve / print process icons", "Portfolio masonry", "CMYK colour bar header"],
    demo: { name: "PrintPress Digital", city: "Lahore" },
  },
  {
    id: "printing-02",
    category: "printing",
    name: "Paper & Ink",
    tagline: "Craft stationery, kraft & black",
    description: "Kraft paper tones, letterpress feel and serif type for wedding cards, stationery and premium packaging printers.",
    style: ["craft", "kraft", "premium"],
    theme: theme({ primary: "#1c1917", primaryFg: "#fff", secondary: "#1c1917", accent: "#b45309", accentFg: "#fff", bg: "#f7f2ea", fg: "#1c1917", muted: "#efe7da", mutedFg: "#6b6259", border: "#e2d8c8", heading: "Playfair Display", body: "Lato", radius: "none", dark: "#1c1917" }),
    brief: {
      header: "Kraft header, serif logo, thin nav.",
      hero: "Stationery flat-lay photo, serif headline, 'Wedding cards' CTA.",
      signature: "Portfolio gallery central; services as letterpress-style cards with embossed borders (CSS).",
      layout: "Paper textures, square corners, serif.",
    },
    overrides: { hero: { eyebrow: "Wedding cards · Packaging · Stationery", title: { en: "Printed with craft and care", ur: "مہارت اور خیال سے چھپا ہوا" } } },
    features: ["Portfolio-central home page", "Letterpress-style embossed service cards", "Kraft & black craft palette"],
    demo: { name: "Paper & Ink Press", city: "Karachi" },
  },
  {
    id: "printing-03",
    category: "printing",
    name: "QuickPrint 24",
    tagline: "Fast turnaround, orange & black",
    description: "Speed-focused orange and black with countdown-style messaging, price estimator and same-day pickup emphasis.",
    style: ["fast", "orange", "urgent"],
    theme: theme({ primary: "#f97316", primaryFg: "#111111", secondary: "#111111", accent: "#111111", accentFg: "#fff", bg: "#ffffff", fg: "#111111", muted: "#fff7ed", mutedFg: "#6b7280", heading: "Barlow Condensed", body: "Barlow", radius: "sm", dark: "#111111" }),
    brief: {
      header: "Black header, orange condensed logo, 'Order in 24h' badge.",
      hero: "Bold headline with '24' large, quick-quote card (PriceEstimator) beside.",
      signature: "Price estimator on home; services with turnaround chips; process compact.",
      layout: "Urgent, condensed type, orange/black.",
    },
    features: ["Price estimator on the home page", "Turnaround chips on services", "Compact process strip"],
    demo: { name: "QuickPrint 24", city: "Islamabad" },
  },
  {
    id: "printing-04",
    category: "printing",
    name: "Signage Studio",
    tagline: "Large-format & signage, dark blue",
    description: "Dark blue and yellow, wide imagery for banners, flex, signboards, vehicle branding and exhibition printing.",
    style: ["signage", "dark-blue", "wide"],
    theme: theme({ primary: "#facc15", primaryFg: "#0f172a", secondary: "#e2e8f0", secondaryFg: "#0f172a", accent: "#38bdf8", accentFg: "#0f172a", bg: "#0f172a", fg: "#e2e8f0", muted: "#1e293b", mutedFg: "#94a3b8", card: "#162036", border: "#2c3a55", heading: "Oswald", body: "Inter", radius: "sm", dark: "#0b1220" }),
    brief: {
      header: "Dark blue header, yellow logo, nav, 'Get a quote'.",
      hero: "Wide banner photo, condensed headline, service chips (Flex, Signboards, Vehicle wraps).",
      signature: "Portfolio as wide landscape tiles; services with size/material notes; brands strip of clients.",
      layout: "Dark, wide, yellow accents.",
    },
    overrides: { hero: { eyebrow: "Flex · Signboards · Vehicle branding", title: { en: "Big prints for big impressions", ur: "بڑے تاثر کے لیے بڑے پرنٹس" } } },
    features: ["Wide landscape portfolio tiles", "Size/material notes on services", "Client logo strip"],
    demo: { name: "Signage Studio", city: "Lahore" },
  },
];
