import { theme, type Blueprint } from "@/templates/catalog/index";

/** 10 travel agency templates */
export const travelBlueprints: Blueprint[] = [
  {
    id: "travel-01",
    category: "travel",
    name: "Horizon Travels",
    tagline: "Classic sky-blue agency",
    description: "Trusted sky-blue and sunny orange layout with package search hero, destinations grid and Umrah highlight for full-service agencies.",
    style: ["classic", "trust", "blue"],
    theme: theme({ primary: "#0284c7", primaryFg: "#fff", secondary: "#0c4a6e", accent: "#f97316", accentFg: "#fff", bg: "#ffffff", fg: "#0f172a", muted: "#f0f9ff", mutedFg: "#64748b", heading: "Poppins", body: "Inter", radius: "lg", dark: "#0c4a6e" }),
    brief: {
      header: "White header with blue top bar (IATA, phone), logo, nav, WhatsApp button.",
      hero: "Beach/mountain photo with PackageSearch card (destination + kind), badges.",
      signature: "Destinations as image tiles with 'from Rs' notes; Umrah block with Kaaba image.",
      layout: "Friendly grid, blue/orange, rounded cards.",
    },
    demo: { name: "Horizon Travels", city: "Lahore" },
  },
  {
    id: "travel-02",
    category: "travel",
    name: "Noor Umrah",
    tagline: "Umrah & Hajj specialist, emerald & gold",
    description: "Emerald and gold with Islamic geometric accents for Umrah/Hajj-focused agencies; packages by tier and group departures.",
    style: ["umrah", "emerald", "gold"],
    theme: theme({ primary: "#047857", primaryFg: "#fff", secondary: "#064e3b", accent: "#d4af37", accentFg: "#064e3b", bg: "#fffdf8", fg: "#06281f", muted: "#ecfdf5", mutedFg: "#4b6b5c", border: "#d9e8e0", heading: "Amiri", body: "Lato", radius: "sm", dark: "#064e3b" }),
    brief: {
      header: "Emerald header, gold serif logo, nav, 'Umrah packages' CTA.",
      hero: "Haram photo with dark gradient, gold headline, package tier chips (Economy/Standard/Premium), group departure dates strip.",
      signature: "Geometric pattern dividers (CSS); Umrah highlights with icon list; testimonials from pilgrims.",
      layout: "Formal, ornamental, emerald/gold.",
    },
    order: ["hero", "umrah", "featuredPackages", "process", "features", "services", "stats", "testimonials", "faq", "cta", "contact", "footer", "seo"],
    overrides: { hero: { eyebrow: "Ministry approved · Umrah · Hajj", title: { en: "Umrah packages with comfort and care" }, primaryCta: { label: { en: "View Umrah packages" }, href: "/packages?kind=UMRAH" } }, featuredPackages: { title: { en: "Umrah & Hajj packages" } } },
    demo: { name: "Noor Umrah Services", city: "Karachi" },
  },
  {
    id: "travel-03",
    category: "travel",
    name: "North Trails",
    tagline: "Adventure tours, mountains, green",
    description: "Forest green and glacier white with big landscape imagery for Hunza, Skardu and northern-areas tour operators.",
    style: ["adventure", "mountain", "photo"],
    theme: theme({ primary: "#166534", primaryFg: "#fff", secondary: "#052e16", accent: "#f59e0b", accentFg: "#052e16", bg: "#fafaf7", fg: "#1c1917", muted: "#f0f4ee", mutedFg: "#5f6b5a", border: "#e2e6dc", heading: "Bricolage Grotesque", body: "Inter", radius: "md", dark: "#052e16" }),
    brief: {
      header: "Transparent header over hero, white nav, solid on scroll.",
      hero: "Full-screen mountain video-like image, huge headline, departure dates chip.",
      signature: "Packages as tall image cards with day count badge; destinations strip horizontal scroll.",
      layout: "Photo-led, green CTAs, wide sections.",
    },
    overrides: { hero: { eyebrow: "Hunza · Skardu · Swat · Naran", title: { en: "Discover the north with expert guides" } }, destinations: { items: [{ name: { en: "Hunza Valley" }, image: "", href: "/packages?destination=Hunza", note: "5 days from Rs 45,000" }, { name: { en: "Skardu" }, image: "", href: "/packages?destination=Skardu", note: "7 days from Rs 65,000" }, { name: { en: "Swat & Kalam" }, image: "", href: "/packages?destination=Swat", note: "3 days from Rs 22,000" }, { name: { en: "Naran & Kaghan" }, image: "", href: "/packages?destination=Naran", note: "4 days from Rs 30,000" }] } },
    demo: { name: "North Trails", city: "Islamabad" },
  },
  {
    id: "travel-04",
    category: "travel",
    name: "JetSet",
    tagline: "Modern ticketing & visa, purple",
    description: "Sleek purple and white with ticket-style cards for air ticketing, visa consultancy and short international trips.",
    style: ["modern", "ticketing", "purple"],
    theme: theme({ primary: "#7c3aed", primaryFg: "#fff", secondary: "#2e1065", accent: "#f472b6", accentFg: "#2e1065", bg: "#ffffff", fg: "#1e1b4b", muted: "#f5f3ff", mutedFg: "#6b7280", heading: "Urbanist", body: "Inter", radius: "xl", dark: "#2e1065" }),
    brief: {
      header: "White header, purple logo, pill nav, 'Get a quote'.",
      hero: "Gradient hero with ticket-shaped search card (perforated edges via CSS), airline logos strip.",
      signature: "Services as ticket-stub cards; packages carousel.",
      layout: "Rounded-xl, gradients, ticket motifs.",
    },
    demo: { name: "JetSet Travel & Tours", city: "Lahore" },
  },
  {
    id: "travel-05",
    category: "travel",
    name: "Safar Luxury",
    tagline: "Luxury honeymoon & Europe, black & gold",
    description: "Black and gold luxury look with serif type for honeymoon, Maldives/Turkey/Europe and premium tailor-made tours.",
    style: ["luxury", "dark", "serif"],
    theme: theme({ primary: "#c9a227", primaryFg: "#111111", secondary: "#f5f5f4", secondaryFg: "#111111", accent: "#ffffff", accentFg: "#111111", bg: "#111111", fg: "#f5f5f4", muted: "#1a1a1a", mutedFg: "#a8a29e", card: "#171717", border: "#2a2a2a", heading: "Cormorant Garamond", body: "Jost", radius: "none", dark: "#000000" }),
    brief: {
      header: "Black header, gold serif logo, spaced uppercase nav.",
      hero: "Full-bleed luxury resort photo, serif headline, 'Plan my trip' CTA.",
      signature: "Packages as large editorial cards; destinations as gold-framed images.",
      layout: "Dark luxury, square corners, gold rules.",
    },
    demo: { name: "Safar Luxury Travel", city: "Karachi" },
  },
  {
    id: "travel-06",
    category: "travel",
    name: "Family Trips",
    tagline: "Friendly family holidays, teal & coral",
    description: "Teal and coral, rounded and cheerful for family vacations, school trips and group tours.",
    style: ["friendly", "family", "colourful"],
    theme: theme({ primary: "#0d9488", primaryFg: "#fff", secondary: "#134e4a", accent: "#fb7185", accentFg: "#fff", bg: "#fffdf9", fg: "#1f2937", muted: "#e6f7f5", mutedFg: "#5b6b6a", heading: "Baloo 2", body: "Nunito", radius: "xl", dark: "#134e4a" }),
    brief: {
      header: "Teal rounded header, playful logo, coral CTA.",
      hero: "Illustrated-feel hero with rounded photo blobs, headline, badges 'Kids travel free under 5'.",
      signature: "Destinations as circular tiles; process as bubbles; testimonials with family photos.",
      layout: "Rounded, pastel bands, friendly.",
    },
    demo: { name: "Family Trips Pakistan", city: "Rawalpindi" },
  },
  {
    id: "travel-07",
    category: "travel",
    name: "Desert Rose",
    tagline: "Dubai & Gulf getaways, sand & sunset",
    description: "Sand, terracotta and sunset gradients for Dubai/Baku/Gulf packages and desert-safari style trips.",
    style: ["warm", "gulf", "gradient"],
    theme: theme({ primary: "#c2410c", primaryFg: "#fff", secondary: "#431407", accent: "#fbbf24", accentFg: "#431407", bg: "#fffaf3", fg: "#2a1a10", muted: "#fdf1e3", mutedFg: "#7c6248", border: "#f3e2cf", heading: "Marcellus", body: "Lato", radius: "lg", dark: "#431407" }),
    brief: {
      header: "Sand header, terracotta logo, nav.",
      hero: "Sunset gradient hero with skyline silhouette, headline, package tabs.",
      signature: "Packages as postcard cards; destinations strip with sunset overlays.",
      layout: "Warm gradients, rounded-lg, postcard motifs.",
    },
    overrides: { hero: { eyebrow: "Dubai · Baku · Istanbul", title: { en: "Sunsets, skylines and unforgettable getaways" } } },
    demo: { name: "Desert Rose Tours", city: "Lahore" },
  },
  {
    id: "travel-08",
    category: "travel",
    name: "Visa Desk",
    tagline: "Visa consultancy first, navy & mint",
    description: "Navy and mint with a document-checklist feel for visa consultants who also sell tickets and packages.",
    style: ["visa", "clean", "navy"],
    theme: theme({ primary: "#1e3a8a", primaryFg: "#fff", secondary: "#0f172a", accent: "#34d399", accentFg: "#052e16", bg: "#ffffff", fg: "#0f172a", muted: "#f1f5f9", mutedFg: "#64748b", heading: "DM Sans", body: "DM Sans", radius: "md", dark: "#0f172a" }),
    brief: {
      header: "White header, navy logo with stamp icon, nav, 'Check visa requirements'.",
      hero: "Two-column: headline + country select CTA card (links to /services), passport photo.",
      signature: "Services block prominent (visa types as checklist cards with 'Documents required'); process with stamps.",
      layout: "Clean, navy/mint, document motifs.",
    },
    order: ["hero", "services", "process", "featuredPackages", "features", "stats", "about", "testimonials", "faq", "cta", "contact", "footer", "seo"],
    overrides: { hero: { eyebrow: "Visit · Study · Work visas", title: { en: "Visa guidance you can trust" }, primaryCta: { label: { en: "Explore visa services" }, href: "/services" } } },
    demo: { name: "Visa Desk Consultants", city: "Islamabad" },
  },
  {
    id: "travel-09",
    category: "travel",
    name: "Wanderly",
    tagline: "Instagram-style travel, magazine grid",
    description: "Magazine-style masonry with big photos and minimal type for young travellers, group trips and content-driven agencies.",
    style: ["magazine", "minimal", "photo"],
    theme: theme({ primary: "#111827", primaryFg: "#fff", secondary: "#111827", accent: "#f43f5e", accentFg: "#fff", bg: "#ffffff", fg: "#111827", muted: "#f9fafb", mutedFg: "#6b7280", heading: "Syne", body: "Inter", radius: "sm", dark: "#111827" }),
    brief: {
      header: "Minimal header, wordmark, tiny nav, Instagram icon.",
      hero: "Masonry hero of 5 photos with headline overlay card.",
      signature: "Gallery block is central; packages as photo cards with minimal captions.",
      layout: "Magazine grid, black/white with rose accent.",
    },
    demo: { name: "Wanderly", city: "Lahore" },
  },
  {
    id: "travel-10",
    category: "travel",
    name: "Corporate Travel Co.",
    tagline: "Business travel, grey & blue, formal",
    description: "Formal grey and blue for corporate travel management: ticketing, hotels, group bookings and MICE.",
    style: ["corporate", "formal", "grey"],
    theme: theme({ primary: "#2563eb", primaryFg: "#fff", secondary: "#1f2937", accent: "#0ea5e9", accentFg: "#fff", bg: "#ffffff", fg: "#1f2937", muted: "#f3f4f6", mutedFg: "#6b7280", heading: "IBM Plex Sans", body: "IBM Plex Sans", radius: "sm", dark: "#1f2937" }),
    brief: {
      header: "Grey header, blue logo, nav, 'Request corporate account'.",
      hero: "Split hero, headline, stats row, client logos (brands section).",
      signature: "Services as formal table-like cards; brands strip; contact CTA for corporate accounts.",
      layout: "Formal grid, restrained colour, sharp corners.",
    },
    overrides: { hero: { eyebrow: "Corporate travel management", title: { en: "Travel logistics for growing companies" }, primaryCta: { label: { en: "Open a corporate account" }, href: "/contact" } } },
    demo: { name: "Corporate Travel Co.", city: "Karachi" },
  },
];
