// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit by hand.
import type { TemplateComponents, TemplateMeta } from "@/templates/types";

import { meta as law_01 } from "@/templates/law/01/meta";

export const TEMPLATE_METAS: TemplateMeta[] = [
  law_01,
];

export const TEMPLATE_LOADERS: Record<string, () => Promise<{ components: TemplateComponents }>> = {
  "law-01": () => import("@/templates/law/01"),
};
