import type { TemplateComponents, TemplateMeta } from "@/templates/types";
import type { CategoryKey } from "@/lib/categories";
import { TEMPLATE_LOADERS, TEMPLATE_METAS } from "@/templates/metas";

/**
 * Template registry.
 *  - `TEMPLATE_METAS` (static) is imported by the super site, admin and seeders.
 *  - `loadTemplateComponents` dynamically imports the React implementation so the
 *    server bundle for a tenant page only pulls in that tenant's template.
 * `metas.ts` is generated by `npm run gen:templates`.
 */
export const TEMPLATES: TemplateMeta[] = TEMPLATE_METAS;

const byId = new Map(TEMPLATES.map((t) => [t.id, t]));

export function getTemplateMeta(id: string): TemplateMeta | undefined {
  return byId.get(id);
}

export function templatesForCategory(category: CategoryKey | string): TemplateMeta[] {
  return TEMPLATES.filter((t) => t.category === category);
}

export async function loadTemplateComponents(id: string): Promise<TemplateComponents> {
  const loader = TEMPLATE_LOADERS[id];
  if (!loader) throw new Error(`Unknown template: ${id}`);
  const mod = await loader();
  return mod.components;
}
