// AUTO-GENERATED by scripts/capture-template-shots.mjs (`npm run shots`) — do not edit by hand.
// Real screenshots of each template's live demo, served from /public/templates/<id>-<device>.webp.

export interface TemplateShot {
  /** intrinsic size of the stored image */
  width: number;
  height: number;
}

export const TEMPLATE_SHOTS: Record<string, { v: string; desktop?: TemplateShot; mobile?: TemplateShot }> = {
  "bakery-01": {
    "v": "1ba999b10b",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "bakery-02": {
    "v": "bfc06302e5",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "bakery-03": {
    "v": "75c420df60",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "bakery-04": {
    "v": "e2c39c7ca1",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "bakery-05": {
    "v": "c0ba467214",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "blades-01": {
    "v": "f3266a67b9",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "blades-02": {
    "v": "6eeb15be54",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "blades-03": {
    "v": "c9a0f5e8a2",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "blades-04": {
    "v": "5205f0d540",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "clothing-01": {
    "v": "3c717f8b0f",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "clothing-02": {
    "v": "b6aa75920f",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "clothing-03": {
    "v": "1c7a370fbc",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "clothing-04": {
    "v": "21cc4b4430",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "electronics-01": {
    "v": "587ce9ff6b",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "electronics-02": {
    "v": "6472fc907d",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "electronics-03": {
    "v": "1f522c23ee",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gifts-01": {
    "v": "e3805c1424",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gifts-02": {
    "v": "53201be240",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gifts-03": {
    "v": "965249f1fa",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gifts-04": {
    "v": "0800946603",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gym-01": {
    "v": "d2930a1cdc",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gym-02": {
    "v": "ba8b9a1cc9",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gym-03": {
    "v": "6c889f6ae1",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gym-04": {
    "v": "e41afebf1e",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "gym-05": {
    "v": "5dc0dbd638",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "kitchen-01": {
    "v": "4554b1adc3",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "kitchen-02": {
    "v": "ffc910679c",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "kitchen-03": {
    "v": "40186da9f0",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "kitchen-04": {
    "v": "62f57c0405",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "law-01": {
    "v": "9149c94538",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "law-02": {
    "v": "27265510f1",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "law-03": {
    "v": "d8784dca6f",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "law-04": {
    "v": "460bcbc968",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "law-05": {
    "v": "31e664062f",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "law-06": {
    "v": "ef9efd9ae9",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "medical-01": {
    "v": "7dab6e5c21",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "medical-02": {
    "v": "b154fc464e",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "medical-03": {
    "v": "0f2065f35d",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-01": {
    "v": "2dc27c0401",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-02": {
    "v": "8516886b1b",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-03": {
    "v": "04488c0ee1",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-04": {
    "v": "8c811be0a3",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-05": {
    "v": "f664bce6b4",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-06": {
    "v": "710ee03692",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-07": {
    "v": "35f727504e",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-08": {
    "v": "6b90c18189",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-09": {
    "v": "9d75fc9d08",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "pizza-10": {
    "v": "3f22a059eb",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "printing-01": {
    "v": "5d61680714",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "printing-02": {
    "v": "08b4dd2446",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "printing-03": {
    "v": "9bb08f7c20",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "printing-04": {
    "v": "415343b2d3",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "realestate-01": {
    "v": "a79c7665de",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "realestate-02": {
    "v": "7fce2240e5",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "realestate-03": {
    "v": "13e4f0e61c",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-01": {
    "v": "202298eb5a",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-02": {
    "v": "825dd96d83",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-03": {
    "v": "9b8e05b111",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-04": {
    "v": "3b1edc10f3",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-05": {
    "v": "c4f1b052f8",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-06": {
    "v": "381ac79b2e",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-07": {
    "v": "0f11f8fdbd",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-08": {
    "v": "e19dc11b7a",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-09": {
    "v": "22786393dd",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "recruiting-10": {
    "v": "9821b30a51",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "shoes-01": {
    "v": "f5379fe38a",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "shoes-02": {
    "v": "0a83016bf1",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "shoes-03": {
    "v": "e4703a2b35",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "shoes-04": {
    "v": "4c6a7dfc4a",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "sports-01": {
    "v": "4117490773",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "sports-02": {
    "v": "fe079ca509",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "sports-03": {
    "v": "d262ce4b99",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "sports-04": {
    "v": "bdcd35d99f",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "sports-05": {
    "v": "84f103a1d0",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-01": {
    "v": "ba46794960",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-02": {
    "v": "7cf50ca980",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-03": {
    "v": "cbd079d288",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-04": {
    "v": "a49d230019",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-05": {
    "v": "3a02c2b76f",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-06": {
    "v": "7aa444e732",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-07": {
    "v": "dcaba6731d",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-08": {
    "v": "2bcaf6af37",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-09": {
    "v": "4108466058",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  },
  "travel-10": {
    "v": "3c92d6b9e5",
    "desktop": {
      "width": 800,
      "height": 2000
    },
    "mobile": {
      "width": 390,
      "height": 2400
    }
  }
};
