import { ls } from "@/lib/i18n";

/** Bilingual UI strings for the travel storefront kit. */
export const ts = {
  packages: ls("Packages", "پیکجز"),
  ourPackages: ls("Our Packages", "ہمارے پیکجز"),
  featuredPackages: ls("Featured Packages", "نمایاں پیکجز"),
  viewAll: ls("View all packages", "تمام پیکجز دیکھیں"),
  allKinds: ls("All", "تمام"),
  destination: ls("Destination", "منزل"),
  anyDestination: ls("Any destination", "کوئی بھی منزل"),
  packageType: ls("Package type", "پیکج کی قسم"),
  anyType: ls("Any type", "کوئی بھی قسم"),
  searchPackages: ls("Search packages", "پیکج تلاش کریں"),
  keyword: ls("Search by name or destination", "نام یا منزل سے تلاش کریں"),
  packagesFound: ls("packages found", "پیکجز ملے"),
  noPackages: ls("No packages match your search.", "آپ کی تلاش سے کوئی پیکج نہیں ملا۔"),
  noPackagesHint: ls("Try another destination or clear the filters.", "کوئی اور منزل آزمائیں یا فلٹرز ہٹائیں۔"),
  clearFilters: ls("Clear filters", "فلٹرز ہٹائیں"),
  days: ls("Days", "دن"),
  nights: ls("Nights", "راتیں"),
  daysNights: ls("days / nights", "دن / راتیں"),
  from: ls("From", "صرف"),
  perPerson: ls("per person", "فی کس"),
  viewPackage: ls("View package", "پیکج دیکھیں"),
  overview: ls("Overview", "جائزہ"),
  itinerary: ls("Itinerary", "سفر کا شیڈول"),
  day: ls("Day", "دن"),
  inclusions: ls("What's included", "پیکج میں شامل"),
  exclusions: ls("Not included", "شامل نہیں"),
  departures: ls("Upcoming departures", "آئندہ روانگیاں"),
  noDepartures: ls("Departures on request", "روانگی درخواست پر"),
  bookThis: ls("Book this package", "یہ پیکج بک کریں"),
  requestBooking: ls("Request Booking", "بکنگ کی درخواست"),
  askWhatsApp: ls("Ask on WhatsApp", "واٹس ایپ پر پوچھیں"),
  backToPackages: ls("Back to all packages", "تمام پیکجز پر واپس"),
  // booking form
  yourName: ls("Full name", "پورا نام"),
  yourPhone: ls("Mobile number", "موبائل نمبر"),
  yourEmail: ls("Email (optional)", "ای میل (اختیاری)"),
  travellers: ls("Travellers", "مسافر"),
  preferredDate: ls("Preferred departure date", "روانگی کی مطلوبہ تاریخ"),
  message: ls("Message (optional)", "پیغام (اختیاری)"),
  booked: ls("Booking request received! Our team will call you shortly to confirm.", "بکنگ کی درخواست موصول ہو گئی! ہماری ٹیم جلد آپ کو کال کرے گی۔"),
  bookAnother: ls("Browse more packages", "مزید پیکجز دیکھیں"),
  // umrah highlights
  umrahTitle: ls("Umrah with peace of mind", "اطمینان کے ساتھ عمرہ"),
  umrahSubtitle: ls("Complete Umrah packages from Pakistan — visa, flights, hotels near Haram and ziyarat, all handled by us.", "پاکستان سے مکمل عمرہ پیکجز — ویزا، فلائٹس، حرم کے قریب ہوٹل اور زیارات، سب ہماری ذمہ داری۔"),
} as const;
