import { ls } from "@/lib/i18n";

/** Module-specific UI strings (the platform-wide ones live in `ui` from `@/lib/i18n`). */
export const sui = {
  shopTitle: ls("Shop", "شاپ"),
  shopSubtitle: ls("Browse our full range and order with cash on delivery.", "ہماری مکمل رینج دیکھیں اور کیش آن ڈیلیوری پر آرڈر کریں۔"),
  results: ls("products", "مصنوعات"),
  noProducts: ls("No products found.", "کوئی مصنوعات نہیں ملیں۔"),
  clearFilters: ls("Clear filters", "فلٹرز صاف کریں"),
  searchPlaceholder: ls("Search products…", "مصنوعات تلاش کریں…"),
  sortBy: ls("Sort", "ترتیب"),
  sortFeatured: ls("Featured", "نمایاں"),
  sortNewest: ls("Newest", "تازہ ترین"),
  sortPriceAsc: ls("Price: low to high", "قیمت: کم سے زیادہ"),
  sortPriceDesc: ls("Price: high to low", "قیمت: زیادہ سے کم"),
  category: ls("Category", "زمرہ"),
  allCategories: ls("All categories", "تمام زمرے"),
  from: ls("From", "شروع"),
  off: ls("OFF", "رعایت"),
  lowStock: ls("Only {n} left", "صرف {n} باقی"),
  quickAdd: ls("Add", "شامل کریں"),
  added: ls("Added to cart", "کارٹ میں شامل ہو گیا"),
  viewCart: ls("View cart", "کارٹ دیکھیں"),
  orderOnWhatsApp: ls("Order on WhatsApp", "واٹس ایپ پر آرڈر کریں"),
  selectOption: ls("Select {name}", "{name} منتخب کریں"),
  unavailableCombo: ls("This combination is not available.", "یہ انتخاب دستیاب نہیں ہے۔"),
  description: ls("Description", "تفصیل"),
  specifications: ls("Specifications", "خصوصیات"),
  details: ls("Details", "تفصیلات"),
  medicalInfo: ls("Medicine information", "دوا کی معلومات"),
  genericName: ls("Generic name", "جنرک نام"),
  manufacturer: ls("Manufacturer", "مینوفیکچرر"),
  dosageForm: ls("Dosage form", "خوراک کی شکل"),
  strength: ls("Strength", "طاقت"),
  prescriptionNote: ls(
    "This medicine requires a valid doctor's prescription. You will be asked to upload it at checkout.",
    "اس دوا کے لیے ڈاکٹر کا درست نسخہ درکار ہے۔ چیک آؤٹ پر آپ سے اسے اپ لوڈ کرنے کو کہا جائے گا۔",
  ),
  relatedProducts: ls("You may also like", "آپ کو یہ بھی پسند آ سکتا ہے"),
  sku: ls("SKU", "ایس کے یو"),
  cartTitle: ls("Your cart", "آپ کا کارٹ"),
  itemsInCart: ls("{n} items", "{n} اشیاء"),
  shippingAtCheckout: ls("Shipping is calculated at checkout.", "ترسیل کا خرچ چیک آؤٹ پر شمار ہوگا۔"),
  proceedToCheckout: ls("Proceed to checkout", "چیک آؤٹ کریں"),
  clearCart: ls("Clear cart", "کارٹ خالی کریں"),
  checkoutTitle: ls("Checkout", "چیک آؤٹ"),
  deliveryDetails: ls("Delivery details", "ترسیل کی تفصیلات"),
  orderSummary: ls("Order summary", "آرڈر کا خلاصہ"),
  selectCity: ls("Select your city", "اپنا شہر منتخب کریں"),
  otherCity: ls("Other city", "دوسرا شہر"),
  enterCity: ls("Enter your city", "اپنا شہر لکھیں"),
  giftMessage: ls("Gift message (optional)", "تحفے کا پیغام (اختیاری)"),
  giftMessageHelp: ls("We will print this on a card with the gift.", "ہم اسے تحفے کے ساتھ کارڈ پر پرنٹ کریں گے۔"),
  ageConfirm: ls("I confirm that I am 18 years of age or older.", "میں تصدیق کرتا/کرتی ہوں کہ میری عمر 18 سال یا زیادہ ہے۔"),
  prescriptionUpload: ls("Upload prescription", "نسخہ اپ لوڈ کریں"),
  prescriptionHelp: ls("One or more items in your cart require a prescription. Upload a clear photo or PDF.", "آپ کے کارٹ میں موجود کچھ اشیاء کے لیے نسخہ درکار ہے۔ واضح تصویر یا PDF اپ لوڈ کریں۔"),
  codOnly: ls("Payment: Cash on Delivery only. Pay the rider when your order arrives.", "ادائیگی: صرف کیش آن ڈیلیوری۔ آرڈر پہنچنے پر رائیڈر کو ادائیگی کریں۔"),
  free: ls("Free", "مفت"),
  estimatedDelivery: ls("Estimated delivery", "متوقع ترسیل"),
  days: ls("days", "دن"),
  minOrderNotice: ls("Minimum order is {amount}.", "کم از کم آرڈر {amount} ہے۔"),
  freeShippingHint: ls("Free shipping on orders above {amount}.", "{amount} سے زیادہ کے آرڈر پر مفت ترسیل۔"),
  couponApplied: ls("Coupon applied", "کوپن لگ گیا"),
  removeCoupon: ls("Remove", "ہٹائیں"),
  placingOrder: ls("Placing order…", "آرڈر دیا جا رہا ہے…"),
  orderingPaused: ls("Online ordering is currently paused. Please contact us on WhatsApp to place an order.", "آن لائن آرڈرنگ فی الحال معطل ہے۔ آرڈر کے لیے واٹس ایپ پر رابطہ کریں۔"),
  orderReceived: ls("Thank you! Your order has been received.", "شکریہ! آپ کا آرڈر موصول ہو گیا ہے۔"),
  orderReceivedSub: ls("We will call or WhatsApp you shortly to confirm. Please keep your phone reachable.", "ہم جلد ہی تصدیق کے لیے کال یا واٹس ایپ کریں گے۔ اپنا فون قابلِ رسائی رکھیں۔"),
  yourOrderNumber: ls("Your order number", "آپ کا آرڈر نمبر"),
  trackTitle: ls("Track your order", "اپنا آرڈر ٹریک کریں"),
  trackHelp: ls("Enter your order number and the mobile number used at checkout.", "اپنا آرڈر نمبر اور چیک آؤٹ پر استعمال شدہ موبائل نمبر درج کریں۔"),
  orderNotFound: ls("No order found with these details.", "ان تفصیلات سے کوئی آرڈر نہیں ملا۔"),
  verifyPhone: ls("Verify your mobile number to view this order.", "یہ آرڈر دیکھنے کے لیے اپنا موبائل نمبر تصدیق کریں۔"),
  orderStatus: ls("Order status", "آرڈر کی حالت"),
  placedOn: ls("Placed on", "تاریخ"),
  deliverTo: ls("Deliver to", "ترسیل کا پتہ"),
  items: ls("Items", "اشیاء"),
  statusPending: ls("Pending", "زیر التواء"),
  statusConfirmed: ls("Confirmed", "تصدیق شدہ"),
  statusProcessing: ls("Processing", "تیاری"),
  statusShipped: ls("Shipped", "روانہ"),
  statusDelivered: ls("Delivered", "پہنچ گیا"),
  statusCancelled: ls("Cancelled", "منسوخ"),
  statusReturned: ls("Returned", "واپس"),
  needHelp: ls("Need help with this order?", "اس آرڈر میں مدد چاہیے؟"),
  featuredTitle: ls("Featured products", "نمایاں مصنوعات"),
  viewAll: ls("View all products", "تمام مصنوعات دیکھیں"),
  uploadRxTitle: ls("Upload your prescription", "اپنا نسخہ اپ لوڈ کریں"),
  uploadRxSub: ls("Send us your doctor's prescription and we will prepare your medicines and call you to confirm.", "اپنے ڈاکٹر کا نسخہ بھیجیں، ہم آپ کی ادویات تیار کر کے تصدیق کے لیے کال کریں گے۔"),
  uploadRxDone: ls("Prescription received. Our pharmacist will contact you shortly.", "نسخہ موصول ہو گیا۔ ہمارا فارماسسٹ جلد رابطہ کرے گا۔"),
  rxFile: ls("Prescription file (photo or PDF)", "نسخے کی فائل (تصویر یا PDF)"),
  rxNotes: ls("Notes (medicines needed, quantity…)", "نوٹس (مطلوبہ ادویات، مقدار…)"),
  page: ls("Page", "صفحہ"),
  of: ls("of", "از"),
  previous: ls("Previous", "پچھلا"),
  next: ls("Next", "اگلا"),
  backToShop: ls("Back to shop", "شاپ پر واپس"),
  each: ls("each", "فی عدد"),
  qty: ls("Qty", "تعداد"),
} as const;

export function fmt(template: string, vars: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (_, k: string) => String(vars[k] ?? ""));
}

export const STATUS_LABEL: Record<string, keyof typeof sui> = {
  PENDING: "statusPending",
  CONFIRMED: "statusConfirmed",
  PROCESSING: "statusProcessing",
  SHIPPED: "statusShipped",
  DELIVERED: "statusDelivered",
  CANCELLED: "statusCancelled",
  RETURNED: "statusReturned",
};
