import { ls } from "@/lib/i18n";

/** Restaurant-specific UI strings (EN + UR). Use with `t(rs.key, lang)`. */
export const rs = {
  viewOrder: ls("View order", "آرڈر دیکھیں"),
  yourOrder: ls("Your order", "آپ کا آرڈر"),
  addToOrder: ls("Add to order", "آرڈر میں شامل کریں"),
  add: ls("Add", "شامل کریں"),
  customize: ls("Customize", "اپنی پسند کے مطابق"),
  from: ls("From", "شروع"),
  size: ls("Size", "سائز"),
  specialNote: ls("Special instructions (optional)", "خصوصی ہدایات (اختیاری)"),
  required: ls("Required", "لازمی"),
  optional: ls("Optional", "اختیاری"),
  chooseUpTo: ls("Choose up to", "زیادہ سے زیادہ"),
  chooseAtLeast: ls("Choose at least", "کم از کم"),
  emptyOrder: ls("Your order is empty", "آپ کا آرڈر خالی ہے"),
  browseMenu: ls("Browse menu", "مینیو دیکھیں"),
  addMore: ls("Add more items", "مزید آئٹمز شامل کریں"),
  clearOrder: ls("Clear order", "آرڈر صاف کریں"),
  proceedToCheckout: ls("Proceed to checkout", "چیک آؤٹ پر جائیں"),
  searchMenu: ls("Search the menu…", "مینیو تلاش کریں…"),
  noResults: ls("No items match your search.", "کوئی آئٹم نہیں ملا۔"),
  orderType: ls("Order type", "آرڈر کی قسم"),
  deliveryArea: ls("Delivery area", "ڈیلیوری ایریا"),
  selectArea: ls("Select your area", "اپنا ایریا منتخب کریں"),
  deliveryAddress: ls("Delivery address", "ڈیلیوری کا پتہ"),
  tableNumber: ls("Table number", "ٹیبل نمبر"),
  minOrder: ls("Minimum order", "کم از کم آرڈر"),
  eta: ls("Estimated time", "متوقع وقت"),
  mins: ls("min", "منٹ"),
  scheduleLater: ls("Schedule for later", "بعد کے لیے شیڈول کریں"),
  scheduleTime: ls("Deliver / pickup at", "ڈیلیوری / پک اپ کا وقت"),
  codNotice: ls("Payment is cash on delivery / at the counter. No advance payment needed.", "ادائیگی ڈیلیوری پر یا کاؤنٹر پر نقد ہو گی۔ پیشگی ادائیگی کی ضرورت نہیں۔"),
  pausedNotice: ls("We are not accepting online orders right now. Please call us.", "ہم اس وقت آن لائن آرڈر قبول نہیں کر رہے۔ براہ کرم کال کریں۔"),
  closedNotice: ls("We are closed right now. You can schedule your order for later.", "ہم اس وقت بند ہیں۔ آپ اپنا آرڈر بعد کے لیے شیڈول کر سکتے ہیں۔"),
  placeOrder: ls("Place order", "آرڈر کریں"),
  placing: ls("Placing order…", "آرڈر ہو رہا ہے…"),
  orderReceived: ls("Order received!", "آرڈر موصول ہو گیا!"),
  trackingIntro: ls("We will update this page as your order progresses.", "آرڈر کی پیش رفت یہاں اپ ڈیٹ ہوتی رہے گی۔"),
  estimated: ls("Estimated", "متوقع"),
  orderCancelled: ls("This order was cancelled.", "یہ آرڈر منسوخ کر دیا گیا۔"),
  verifyPhone: ls("Enter the last 4 digits of the phone number used for this order.", "اس آرڈر کے لیے استعمال ہونے والے فون نمبر کے آخری 4 ہندسے درج کریں۔"),
  verify: ls("View order", "آرڈر دیکھیں"),
  reserveTable: ls("Reserve a table", "ٹیبل بک کریں"),
  guests: ls("Guests", "مہمان"),
  date: ls("Date", "تاریخ"),
  time: ls("Time", "وقت"),
  reservationDone: ls("Reservation request received. We will confirm by phone.", "ریزرویشن کی درخواست موصول ہو گئی۔ ہم فون پر تصدیق کریں گے۔"),
  customCake: ls("Custom cake request", "کسٹم کیک کی درخواست"),
  occasion: ls("Occasion", "موقع"),
  flavour: ls("Flavour", "ذائقہ"),
  weight: ls("Size / weight", "سائز / وزن"),
  servings: ls("Servings (approx.)", "افراد (تقریباً)"),
  dateNeeded: ls("Date needed", "درکار تاریخ"),
  messageOnCake: ls("Message on cake", "کیک پر پیغام"),
  referenceImage: ls("Reference image (optional)", "حوالہ تصویر (اختیاری)"),
  details: ls("Any other details", "دیگر تفصیلات"),
  featured: ls("Featured", "نمایاں"),
  deals: ls("Today's deals", "آج کی ڈیلز"),
  popular: ls("Popular picks", "مقبول انتخاب"),
  seeFullMenu: ls("See full menu", "مکمل مینیو دیکھیں"),
  spicy: ls("Spicy", "مصالحے دار"),
  veg: ls("Veg", "سبزی"),
  bestseller: ls("Bestseller", "بیسٹ سیلر"),
  new: ls("New", "نیا"),
  unavailable: ls("Unavailable", "دستیاب نہیں"),
  ordersPaused: ls("Online orders paused", "آن لائن آرڈر معطل"),
  items: ls("items", "آئٹمز"),
  item: ls("item", "آئٹم"),
  deliveringTo: ls("Delivering to", "ڈیلیوری"),
  callUs: ls("Call us", "کال کریں"),
  scheduledFor: ls("Scheduled for", "شیڈول"),
  tooFewSelected: ls("Please make the required selections.", "براہ کرم لازمی انتخاب کریں۔"),
} as const;
