import { ls } from "@/lib/i18n";

/** Bilingual UI strings used by the recruiting storefront kit. */
export const rs = {
  jobs: ls("Jobs", "نوکریاں"),
  latestJobs: ls("Latest Jobs", "تازہ ترین نوکریاں"),
  featuredJobs: ls("Featured Jobs", "نمایاں نوکریاں"),
  browseAll: ls("Browse all jobs", "تمام نوکریاں دیکھیں"),
  keyword: ls("Job title, company or keyword", "عہدہ، کمپنی یا کلیدی لفظ"),
  location: ls("Location", "مقام"),
  anyLocation: ls("Any location", "کوئی بھی مقام"),
  jobType: ls("Job type", "نوکری کی قسم"),
  anyType: ls("Any type", "کوئی بھی قسم"),
  country: ls("Country", "ملک"),
  anyCountry: ls("Any country", "کوئی بھی ملک"),
  findJobs: ls("Find Jobs", "نوکریاں تلاش کریں"),
  clearFilters: ls("Clear filters", "فلٹرز ہٹائیں"),
  resultsFound: ls("jobs found", "نوکریاں ملیں"),
  noJobs: ls("No jobs match your search right now.", "فی الحال آپ کی تلاش سے کوئی نوکری نہیں ملی۔"),
  noJobsHint: ls("Try a different keyword or clear the filters.", "کوئی اور لفظ آزمائیں یا فلٹرز ہٹائیں۔"),
  salary: ls("Salary", "تنخواہ"),
  salaryNegotiable: ls("Market competitive", "مارکیٹ کے مطابق"),
  experience: ls("Experience", "تجربہ"),
  vacancies: ls("Vacancies", "آسامیاں"),
  deadline: ls("Apply by", "آخری تاریخ"),
  closed: ls("Applications closed", "درخواستیں بند"),
  posted: ls("Posted", "شائع ہوا"),
  department: ls("Department", "شعبہ"),
  company: ls("Company", "کمپنی"),
  description: ls("Job Description", "نوکری کی تفصیل"),
  requirements: ls("Requirements", "تقاضے"),
  applyNow: ls("Apply Now", "ابھی درخواست دیں"),
  applyForJob: ls("Apply for this job", "اس نوکری کے لیے درخواست دیں"),
  shareWhatsApp: ls("Share on WhatsApp", "واٹس ایپ پر شیئر کریں"),
  askWhatsApp: ls("Ask on WhatsApp", "واٹس ایپ پر پوچھیں"),
  backToJobs: ls("Back to all jobs", "تمام نوکریوں پر واپس"),
  browseByDepartment: ls("Browse by department", "شعبے کے لحاظ سے دیکھیں"),
  positions: ls("positions", "آسامیاں"),
  // apply form
  yourName: ls("Full name", "پورا نام"),
  yourPhone: ls("Mobile number", "موبائل نمبر"),
  yourEmail: ls("Email (optional)", "ای میل (اختیاری)"),
  yourCity: ls("City", "شہر"),
  selectExperience: ls("Select experience", "تجربہ منتخب کریں"),
  coverLetter: ls("Cover letter / short intro (optional)", "تعارفی خط (اختیاری)"),
  uploadCv: ls("Upload CV (PDF or Word)", "سی وی اپ لوڈ کریں (PDF یا Word)"),
  cvRequired: ls("Please upload your CV.", "براہ کرم اپنا سی وی اپ لوڈ کریں۔"),
  submitApplication: ls("Submit Application", "درخواست جمع کریں"),
  applied: ls("Your application has been received. We will contact shortlisted candidates.", "آپ کی درخواست موصول ہو گئی ہے۔ ہم منتخب امیدواروں سے رابطہ کریں گے۔"),
  applyAnother: ls("Browse more jobs", "مزید نوکریاں دیکھیں"),
  alreadyApplied: ls("We already have your application for this job. We will contact shortlisted candidates.", "اس نوکری کے لیے آپ کی درخواست پہلے ہی موصول ہو چکی ہے۔ ہم منتخب امیدواروں سے رابطہ کریں گے۔"),
  jobUnavailable: ls("This job is no longer available.", "یہ نوکری اب دستیاب نہیں ہے۔"),
  jobClosed: ls("Applications for this job are closed.", "اس نوکری کے لیے درخواستیں بند ہو چکی ہیں۔"),
  cvInvalid: ls("Your CV could not be verified. Please upload it again.", "آپ کے سی وی کی تصدیق نہیں ہو سکی۔ براہ کرم دوبارہ اپ لوڈ کریں۔"),
  cvWrongType: ls("Please upload your CV as a PDF or Word document.", "براہ کرم سی وی PDF یا Word فائل کی صورت میں اپ لوڈ کریں۔"),
  // employer form
  employerTitle: ls("Hire staff through us", "ہمارے ذریعے عملہ بھرتی کریں"),
  companyName: ls("Company name", "کمپنی کا نام"),
  contactPerson: ls("Contact person", "رابطہ شخص"),
  positionsNeeded: ls("Positions needed (e.g. Welders, Accountant)", "درکار آسامیاں (مثلاً ویلڈر، اکاؤنٹنٹ)"),
  headcount: ls("Number of staff", "عملے کی تعداد"),
  workLocation: ls("Work location (city / country)", "کام کا مقام (شہر / ملک)"),
  employerMessage: ls("Tell us about the roles, salary range and timeline", "کردار، تنخواہ اور مدت کے بارے میں بتائیں"),
  sendRequest: ls("Send Request", "درخواست بھیجیں"),
} as const;
